import type { ReferenceEntry, VisualRole } from './entries'

// Encyclopedia-only definitions. These are written for the new reference
// experience and intentionally differ from the classic study glossary.
// Every diagram is a simplified, time-ordered model: real message types,
// timings and rules depend on each payment scheme.

type Step = [from: number, to: number, label: string, detail: string, entry?: string]
type Cast = { actors: string[]; roles: VisualRole[] }
export const p2p: Cast = { actors: ['CUSTOMER_A', 'BANK_A', 'PAYMENT_SYSTEM', 'BANK_B', 'CUSTOMER_B'], roles: ['party', 'agent', 'infrastructure', 'agent', 'party'] }
const banks: Cast = { actors: ['BANK_A', 'PAYMENT_SYSTEM', 'BANK_B'], roles: ['agent', 'infrastructure', 'agent'] }
const customerBank: Cast = { actors: ['CUSTOMER_A', 'BANK_A'], roles: ['party', 'agent'] }
export function seq(title: string, cast: Cast, steps: Step[]): NonNullable<ReferenceEntry['diagram']> {
  return { title, actors: cast.actors, actorRoles: cast.roles, steps: steps.map(([from, to, label, detail, entry]) => ({ from, to, label, detail, entry })) }
}

type Concept = Omit<ReferenceEntry, 'category' | 'sources'> & { sources?: ReferenceEntry['sources'] }

export const conceptEntries: Concept[] = [
  // ── Systems and infrastructure ──────────────────────────────────────────
  {
    id: 'payment-system', title: 'Sistema de pagos', subtitle: 'Reglas + participantes + infraestructura',
    summary: 'Conjunto de reglas, acuerdos, participantes e infraestructura técnica que permite transferir dinero entre cuentas de distintas instituciones.',
    plain: 'Es "la carretera" por la que viajan los pagos entre bancos: no es un banco ni una app, sino el acuerdo y la plataforma que permiten que un banco le pague a otro.',
    aliases: ['payment system', 'sistema de pago'],
    facts: [{ label: 'Lo que lo forma', value: 'Reglas (quién puede participar, horarios, límites), participantes (bancos y otras entidades) y una plataforma que procesa las instrucciones.' }, { label: 'Lo que hace', value: 'Recibe instrucciones de un participante, las valida, las entrega al otro y organiza la liquidación de lo que se deben.' }, { label: 'Lo que no es', value: 'No es el canal del cliente (la app o la web) ni el banco: es la capa que conecta a los bancos entre sí.' }],
    analogy: { text: 'Como una red de autopistas con peajes y normas de tránsito: los autos (pagos) son de cada conductor, pero las vías y las reglas son comunes.', limit: 'Un sistema de pagos además gestiona riesgos y deudas entre participantes, algo que una carretera no hace.' },
    example: { title: 'Dos bancos, una red', text: 'BANK_A y BANK_B participan en PAYMENT_SYSTEM. Cuando CUSTOMER_A paga a CUSTOMER_B, BANK_A envía la instrucción por PAYMENT_SYSTEM.', outcome: 'Sin un sistema común, cada par de bancos tendría que acordar su propia conexión y sus reglas.' },
    diagram: seq('Un pago atraviesa el sistema', p2p, [
      [0, 1, 'Orden de pago', 'El cliente pide pagar desde el canal de su banco.'],
      [1, 2, 'Instrucción', 'BANK_A envía la instrucción al sistema según sus reglas (en ISO 20022, típicamente un pacs.008).', 'pacs.008'],
      [2, 3, 'Entrega', 'El sistema valida y entrega la instrucción al banco del beneficiario.'],
      [3, 2, 'Respuesta', 'BANK_B acepta o rechaza. El sistema organiza la liquidación entre bancos.'],
      [3, 4, 'Abono', 'BANK_B acredita la cuenta del beneficiario.'],
    ]),
    related: ['payment-scheme', 'participant', 'settlement-system', 'fast-payments'],
  },
  {
    id: 'payment-scheme', title: 'Esquema de pagos', subtitle: 'El reglamento de un servicio de pago',
    summary: 'El conjunto de reglas de negocio y técnicas que deben cumplir los participantes para ofrecer un servicio de pago concreto.',
    plain: 'Es el "reglamento del juego": dice qué mensajes se usan, en qué versión, cuánto tiempo hay para responder, qué códigos de error existen y qué pasa si algo falla.',
    aliases: ['scheme', 'rulebook', 'reglas del esquema'],
    facts: [{ label: 'Qué define', value: 'Tipos de pago admitidos, versión de mensajes ISO 20022, campos obligatorios, códigos de motivo, tiempos máximos y responsabilidades.' }, { label: 'Por qué importa', value: 'ISO 20022 ofrece un vocabulario amplio; el esquema decide qué parte de él se usa y cómo.' }, { label: 'Esquema vs sistema', value: 'El esquema son las reglas; el sistema es la plataforma que las ejecuta. A veces los gestiona la misma organización.' }],
    analogy: { text: 'El idioma es el mismo (ISO 20022), pero cada torneo tiene su propio reglamento: cuántos jugadores, cuánto dura el partido, qué es falta.', limit: 'Un reglamento de pagos también tiene efectos legales y financieros sobre los participantes.' },
    example: { title: 'Un campo, dos reglas', text: 'Un esquema puede exigir que EndToEndId tenga una referencia real; otro puede admitir NOTPROVIDED.', outcome: 'Por eso un XML válido según ISO puede ser rechazado por un esquema concreto.' },
    caution: 'Lo que dice ISO 20022 no es automáticamente lo que exige un esquema. Siempre hay que leer la guía de uso aplicable.',
    diagram: seq('El esquema decide qué se acepta', banks, [
      [0, 1, 'Instrucción', 'BANK_A envía un pago con el formato y la versión que pide el esquema.'],
      [1, 0, 'Rechazo por regla', 'Si falta un dato que el esquema exige, el sistema puede rechazar aunque el XML sea válido según ISO.', 'reject'],
      [0, 1, 'Instrucción corregida', 'BANK_A reenvía cumpliendo las reglas del esquema.'],
      [1, 2, 'Entrega', 'El pago continúa hacia BANK_B.'],
    ]),
    related: ['payment-system', 'iso20022', 'validation', 'fast-payments'],
  },
  {
    id: 'participant', title: 'Participante', subtitle: 'Quién está conectado al sistema',
    summary: 'Institución admitida en un sistema de pagos que puede enviar y recibir instrucciones y que asume obligaciones según las reglas del sistema.',
    plain: 'Es un banco o entidad "con carnet de socio" del sistema de pagos: está conectado, cumple sus reglas y puede pagar y cobrar a través de él.',
    aliases: ['participante directo', 'participante indirecto', 'member'],
    facts: [{ label: 'Directo', value: 'Se conecta y liquida por sí mismo en el sistema.' }, { label: 'Indirecto', value: 'Accede a través de otro participante que lo representa y liquida por él.' }, { label: 'Obligaciones', value: 'Cumplir horarios, formatos, tiempos de respuesta y mantener fondos para liquidar.' }],
    analogy: { text: 'Como un socio de un club: puede usar las instalaciones, pero debe pagar su cuota y respetar las normas.', limit: 'Ser participante implica riesgos financieros y supervisión que un club no tiene.' },
    example: { title: 'Directo e indirecto', text: 'BANK_A es participante directo. BANK_C, más pequeño, envía sus pagos a través de BANK_A.', outcome: 'Para el sistema, la instrucción llega desde BANK_A aunque el cliente sea de BANK_C.' },
    diagram: seq('Participante directo e indirecto', { actors: ['BANK_C', 'BANK_A', 'PAYMENT_SYSTEM', 'BANK_B'], roles: ['agent', 'agent', 'infrastructure', 'agent'] }, [
      [0, 1, 'Pago de un cliente de BANK_C', 'BANK_C no está conectado; entrega el pago a BANK_A, que lo representa.'],
      [1, 2, 'Instrucción', 'BANK_A, participante directo, envía la instrucción al sistema.'],
      [2, 3, 'Entrega', 'BANK_B recibe el pago como de cualquier otro participante.'],
    ]),
    related: ['payment-system', 'agent', 'settlement-account'],
  },
  {
    id: 'payment-network', title: 'Red de pagos', subtitle: 'Las conexiones entre participantes',
    summary: 'Término amplio para el conjunto de conexiones, técnicas y comerciales, que permite que los participantes se envíen pagos entre sí.',
    plain: 'Es "quién está conectado con quién" para mover pagos. A veces se usa como sinónimo de sistema de pagos, pero pone el foco en las conexiones.',
    aliases: ['network', 'red'],
    facts: [{ label: 'Foco', value: 'Conectividad: cómo llegan las instrucciones de un participante a otro.' }, { label: 'Uso informal', value: 'Muchos textos dicen "red" cuando hablan del sistema completo; conviene preguntar a qué se refieren.' }],
    analogy: { text: 'Como el mapa de líneas de un metro: muestra qué estaciones están conectadas.', limit: 'El mapa no explica cómo se cobra el pasaje: en pagos, eso sería la liquidación.' },
    example: { title: 'Varias conexiones', text: 'BANK_A llega a BANK_B a través de PAYMENT_SYSTEM y a BANK_D mediante un corresponsal.', outcome: 'Son dos caminos distintos dentro de la red del banco.' },
    diagram: seq('Una red, varios caminos', { actors: ['BANK_A', 'PAYMENT_SYSTEM', 'BANK_B', 'BANK_D'], roles: ['agent', 'infrastructure', 'agent', 'agent'] }, [
      [0, 1, 'Camino 1', 'BANK_A usa el sistema común para llegar a BANK_B.'],
      [1, 2, 'Entrega', 'El sistema entrega el pago a BANK_B.'],
      [0, 3, 'Camino 2', 'Para BANK_D, BANK_A usa una relación directa (por ejemplo, de corresponsalía).'],
    ]),
    related: ['payment-system', 'payment-rail', 'participant'],
  },
  {
    id: 'payment-rail', title: 'Rail de pagos', subtitle: 'El tipo de vía por el que viaja un pago',
    summary: 'Expresión informal para la infraestructura concreta que transporta un pago: un sistema inmediato, una ACH, un RTGS, una red de tarjetas.',
    plain: 'Es "el carril" que se elige para mandar el pago. El mismo pago podría ir por un carril rápido (inmediato) o por uno más lento y barato (lotes).',
    aliases: ['rail', 'rails', 'riel'],
    facts: [{ label: 'Ejemplos', value: 'Pagos inmediatos, ACH por lotes, RTGS para grandes importes, redes de tarjetas.' }, { label: 'La decisión', value: 'El banco elige el rail según importe, urgencia, coste y lo que acepte el beneficiario.' }],
    analogy: { text: 'Como elegir entre envío exprés, estándar o de carga: el paquete es el mismo, cambia la vía y el tiempo.', limit: 'Cada rail tiene reglas, horarios y formas de liquidar diferentes.' },
    example: { title: 'Mismo pago, dos rails', text: 'Un pago urgente de bajo importe va por el sistema inmediato; una nómina de 500 pagos va por ACH.', outcome: 'El cliente puede ver el mismo resultado final con tiempos distintos.' },
    diagram: seq('Elegir el rail', { actors: ['CUSTOMER_A', 'BANK_A', 'SISTEMA INMEDIATO', 'ACH'], roles: ['party', 'agent', 'infrastructure', 'infrastructure'] }, [
      [0, 1, 'Pago urgente', 'El cliente necesita que llegue en segundos.'],
      [1, 2, 'Rail inmediato', 'BANK_A lo envía por el sistema de pagos inmediatos.'],
      [0, 1, 'Lote de nómina', 'Muchos pagos sin urgencia de segundos.'],
      [1, 3, 'Rail por lotes', 'BANK_A los envía por la ACH en el siguiente ciclo.'],
    ]),
    related: ['payment-network', 'ach', 'rtgs', 'fast-payments'],
  },
  {
    id: 'ach', title: 'ACH', subtitle: 'Cámara de compensación automatizada',
    summary: 'Sistema que recibe pagos de muchos participantes, los procesa por lotes o ciclos y calcula cuánto se deben entre sí para liquidar solo las diferencias.',
    plain: 'Es una central que junta los pagos entre bancos y, en vez de mover cada uno, calcula el saldo final de cada banco al cierre del ciclo.',
    aliases: ['automated clearing house', 'cámara de compensación', 'batch', 'lotes'],
    facts: [{ label: 'Cómo trabaja', value: 'Agrupa pagos por ciclos, compensa (netea) lo que se deben los bancos y liquida las posiciones resultantes.' }, { label: 'Ventaja', value: 'Necesita menos liquidez: se mueve solo la diferencia, no cada pago.' }, { label: 'Tiempo', value: 'Tradicionalmente diferida; hoy muchas ACH tienen varios ciclos al día.' }],
    analogy: { text: 'Como amigos que anotan quién pagó qué durante la semana y el domingo cada uno transfiere solo lo que le toca.', limit: 'Una ACH además tiene garantías, horarios y reglas legales sobre cuándo es firme cada pago.' },
    example: { title: 'Compensar un ciclo', text: 'En un ciclo, BANK_A envía 180 XXX a BANK_B y BANK_B envía 120 XXX a BANK_A.', outcome: 'Se liquida una posición neta de 60 XXX de BANK_A hacia BANK_B.' },
    diagram: seq('Un ciclo de ACH', { actors: ['BANK_A', 'ACH', 'BANK_B', 'LIQUIDACIÓN'], roles: ['agent', 'infrastructure', 'agent', 'infrastructure'] }, [
      [0, 1, 'Lote de pagos', 'BANK_A entrega sus pagos del ciclo.'],
      [2, 1, 'Lote de pagos', 'BANK_B entrega los suyos.'],
      [1, 2, 'Pagos a abonar', 'La ACH entrega a cada banco los pagos que debe acreditar a sus clientes.'],
      [1, 3, 'Posiciones netas', 'Calcula cuánto debe o recibe cada banco y lo envía a liquidar.', 'net-settlement'],
      [3, 2, 'Liquidación', 'Se mueven solo las diferencias entre cuentas de liquidación.'],
    ]),
    related: ['net-settlement', 'clearing', 'rtgs', 'payment-rail'],
  },
  {
    id: 'clearing-system', title: 'Sistema de compensación', subtitle: 'Prepara lo que se va a liquidar',
    summary: 'Infraestructura que recibe, valida y ordena las instrucciones de pago entre participantes y calcula sus obligaciones antes de liquidarlas.',
    plain: 'Es la "contabilidad previa": revisa los pagos, comprueba que estén bien y calcula quién le debe cuánto a quién. Luego otro paso (la liquidación) mueve el dinero.',
    aliases: ['clearing system', 'CSM', 'clearing and settlement mechanism'],
    facts: [{ label: 'Funciones', value: 'Recibir y validar instrucciones, enrutarlas, confirmar y calcular posiciones.' }, { label: 'Relación con liquidar', value: 'A veces la misma plataforma compensa y liquida; aun así son funciones distintas.' }],
    analogy: { text: 'Como el árbitro que anota los puntos: decide el marcador, pero no entrega el premio.', limit: 'En algunos sistemas inmediatos compensar y liquidar ocurren casi al mismo tiempo.' },
    example: { title: 'Validar antes de mover', text: 'El sistema recibe un pago de BANK_A con un BIC de destino inexistente.', outcome: 'Lo rechaza en la compensación: no llega a liquidarse.' },
    diagram: seq('Compensar antes de liquidar', banks, [
      [0, 1, 'Instrucción', 'BANK_A envía el pago.'],
      [1, 0, 'Validación', 'El sistema comprueba formato, participante y reglas; si algo falla, rechaza aquí.'],
      [1, 2, 'Entrega', 'Si es válido, lo entrega a BANK_B y registra la obligación.'],
      [1, 0, 'Posición actualizada', 'La obligación entre bancos queda lista para liquidarse.', 'settlement'],
    ]),
    related: ['clearing', 'settlement', 'ach', 'payment-system'],
  },
  {
    id: 'rtgs', title: 'RTGS', subtitle: 'Liquidación bruta en tiempo real',
    summary: 'Sistema que liquida cada pago de forma individual (bruta) y en el momento (tiempo real), normalmente en cuentas en el banco central.',
    plain: 'Cada pago se paga completo y al instante, uno por uno. No se espera al cierre ni se compensan pagos entre sí.',
    aliases: ['real time gross settlement', 'LBTR', 'liquidación bruta'],
    facts: [{ label: 'Bruta', value: 'Pago por pago, sin compensar.' }, { label: 'Tiempo real', value: 'Se liquida en cuanto hay fondos y se procesa.' }, { label: 'Uso típico', value: 'Pagos de alto valor entre bancos y liquidación de otros sistemas.' }],
    analogy: { text: 'Como pagar cada compra en efectivo al momento, en lugar de abrir una cuenta y pagar a fin de mes.', limit: 'Requiere más liquidez: cada pago necesita fondos disponibles en ese instante.' },
    example: { title: 'Un pago de alto valor', text: 'BANK_A debe 1.000.000 XXX a BANK_B por una operación urgente.', outcome: 'En el RTGS se debita la cuenta de BANK_A y se acredita la de BANK_B de inmediato y de forma firme.' },
    diagram: seq('Un pago en RTGS', { actors: ['BANK_A', 'RTGS', 'BANK_B'], roles: ['agent', 'infrastructure', 'agent'] }, [
      [0, 1, 'Pago', 'BANK_A instruye un pago individual.'],
      [1, 0, 'Débito', 'El RTGS comprueba fondos y debita la cuenta de BANK_A.'],
      [1, 2, 'Crédito firme', 'Acredita la cuenta de BANK_B. El pago queda liquidado.', 'finality'],
    ]),
    related: ['gross-settlement', 'settlement-system', 'finality', 'ach'],
  },
  {
    id: 'settlement-account', title: 'Cuenta de liquidación', subtitle: 'Donde se mueve el dinero entre bancos',
    summary: 'Cuenta que un participante mantiene en el agente de liquidación (a menudo el banco central) para pagar y cobrar sus obligaciones en el sistema.',
    plain: 'Es la "cuenta del banco en el banco de los bancos". Cuando BANK_A le paga a BANK_B, el dinero sale de la cuenta de liquidación de A y entra en la de B.',
    aliases: ['settlement account', 'cuenta en el banco central'],
    facts: [{ label: 'Dueño', value: 'El participante (el banco), no sus clientes.' }, { label: 'Uso', value: 'Liquidar obligaciones interbancarias; puede requerir saldo previo o garantías.' }],
    analogy: { text: 'Como la caja común de una tienda: los cobros de los clientes van a sus cuentas, pero las cuentas con proveedores se pagan desde la caja.', limit: 'El modelo concreto (prefondeo, crédito intradía) depende del sistema.' },
    example: { title: 'Dos niveles', text: 'CUSTOMER_A tiene su cuenta en BANK_A; BANK_A tiene su cuenta de liquidación en el agente de liquidación.', outcome: 'Un pago mueve dinero en ambos niveles: cliente-banco y banco-banco.' },
    diagram: seq('Dos niveles de cuentas', { actors: ['CUSTOMER_A', 'BANK_A', 'AGENTE DE LIQUIDACIÓN', 'BANK_B', 'CUSTOMER_B'], roles: ['party', 'agent', 'infrastructure', 'agent', 'party'] }, [
      [0, 1, 'Débito al cliente', 'BANK_A descuenta el importe de la cuenta de CUSTOMER_A.'],
      [1, 2, 'Débito interbancario', 'Sale dinero de la cuenta de liquidación de BANK_A.'],
      [2, 3, 'Crédito interbancario', 'Entra en la cuenta de liquidación de BANK_B.'],
      [3, 4, 'Crédito al cliente', 'BANK_B abona la cuenta de CUSTOMER_B.'],
    ]),
    related: ['settlement', 'participant', 'settlement-system'],
  },

  // ── Settlement ───────────────────────────────────────────────────────────
  {
    id: 'gross-settlement', title: 'Liquidación bruta', subtitle: 'Uno por uno, completo',
    summary: 'Modelo en el que cada pago se liquida individualmente por su importe total, sin compensarlo con otros pagos.',
    plain: 'Cada pago se paga entero y por separado. Si BANK_A paga 3 veces a BANK_B, hay 3 movimientos de dinero.',
    aliases: ['gross', 'bruta'],
    facts: [{ label: 'Ventaja', value: 'Cada pago queda cerrado sin depender de los demás.' }, { label: 'Coste', value: 'Necesita más liquidez que la liquidación neta.' }],
    analogy: { text: 'Pagar cada café en el momento en vez de pagar la cuenta del mes.', limit: 'Los sistemas brutos pueden usar mecanismos para ahorrar liquidez sin dejar de ser brutos.' },
    example: { title: 'Tres pagos', text: 'BANK_A paga 100, 50 y 30 XXX a BANK_B.', outcome: 'Se hacen tres liquidaciones de 100, 50 y 30 XXX.' },
    diagram: seq('Liquidación pago por pago', { actors: ['BANK_A', 'LIQUIDACIÓN', 'BANK_B'], roles: ['agent', 'infrastructure', 'agent'] }, [
      [0, 1, 'Pago 1 · 100', 'Se liquida completo.'], [1, 2, 'Crédito 100', 'BANK_B recibe 100.'],
      [0, 1, 'Pago 2 · 50', 'Otro movimiento independiente.'], [1, 2, 'Crédito 50', 'BANK_B recibe 50.'],
    ]),
    related: ['net-settlement', 'rtgs', 'settlement'],
  },
  {
    id: 'net-settlement', title: 'Liquidación neta', subtitle: 'Solo se paga la diferencia',
    summary: 'Modelo en el que las obligaciones entre participantes se compensan durante un periodo y se liquida únicamente el saldo resultante.',
    plain: 'Se suman todos los pagos de ida y vuelta y se paga solo la diferencia. Menos movimientos de dinero, pero hay que esperar al cálculo.',
    aliases: ['net', 'neto', 'netting', 'DNS'],
    facts: [{ label: 'Ventaja', value: 'Ahorra mucha liquidez.' }, { label: 'Riesgo', value: 'Si un banco no paga su saldo, afecta a los demás; por eso hay garantías y reglas.' }, { label: 'Variante', value: 'Algunos sistemas inmediatos abonan al cliente al instante y liquidan entre bancos de forma neta después.' }],
    analogy: { text: 'Dos vecinos que se prestan cosas todo el mes y a fin de mes saldan solo la diferencia.', limit: 'Calcular la diferencia no es pagarla: hasta que se liquida, la deuda sigue abierta.' },
    example: { title: 'Ida y vuelta', text: 'BANK_A envía 180 XXX a BANK_B; BANK_B envía 120 XXX a BANK_A.', outcome: 'Posición neta: BANK_A paga 60 XXX a BANK_B.' },
    diagram: seq('Compensar y liquidar el neto', { actors: ['BANK_A', 'SISTEMA', 'BANK_B'], roles: ['agent', 'infrastructure', 'agent'] }, [
      [0, 1, 'Pagos A→B · 180', 'Se registran durante el ciclo.'],
      [2, 1, 'Pagos B→A · 120', 'También se registran.'],
      [1, 0, 'Posición: debes 60', 'Al cierre, el sistema calcula el neto.'],
      [1, 2, 'Liquidación 60', 'Solo se mueve la diferencia.', 'settlement'],
    ]),
    related: ['gross-settlement', 'ach', 'clearing', 'settlement'],
  },
  {
    id: 'finality', title: 'Firmeza', subtitle: 'Cuando ya no hay vuelta atrás',
    summary: 'Momento definido por las reglas del sistema (y la ley) a partir del cual una liquidación es irrevocable e incondicional.',
    plain: 'Es el punto en que el pago ya es definitivo: aunque un banco quiebre o alguien se arrepienta, ese movimiento no se deshace.',
    aliases: ['settlement finality', 'irrevocable', 'firmeza de la liquidación'],
    facts: [{ label: 'Quién lo define', value: 'Las reglas del sistema y el marco legal, no el mensaje.' }, { label: 'Después de la firmeza', value: 'Para "deshacer" un pago hay que hacer otro pago en sentido contrario (por ejemplo, una devolución).' }],
    analogy: { text: 'Como un cheque que ya se cobró: no se puede "descobrar", solo devolver el dinero con otro pago.', limit: 'Cada jurisdicción define exactamente cuándo y cómo se alcanza.' },
    example: { title: 'Error después de liquidar', text: 'BANK_A envió por error 250 XXX y el pago ya es firme.', outcome: 'No se puede cancelar: se pide al beneficiario una devolución, que será un nuevo movimiento.' },
    caution: 'Un mensaje "aceptado" no siempre significa firme. La firmeza la marca la liquidación según las reglas.',
    diagram: seq('Antes y después de la firmeza', banks, [
      [0, 1, 'Instrucción', 'Antes de liquidar, aún podría rechazarse o cancelarse según las reglas.'],
      [1, 2, 'Liquidación firme', 'A partir de aquí el movimiento es irrevocable.'],
      [2, 0, 'Devolución (nuevo pago)', 'Si hay que revertir, se hace con otro movimiento, no deshaciendo el anterior.', 'pacs.004'],
    ]),
    related: ['settlement', 'rtgs', 'return', 'recall'],
  },

  // ── Roles ────────────────────────────────────────────────────────────────
  {
    id: 'agent', title: 'Agente', subtitle: 'Institución que actúa en el pago',
    summary: 'En ISO 20022, una institución financiera que interviene en la cadena del pago prestando servicio a una parte o pasando la instrucción a otra institución.',
    plain: 'El "agente" es el banco. La persona o empresa que paga o cobra es la "parte"; el banco que la atiende es su agente.',
    aliases: ['agent', 'institución financiera', 'FI'],
    facts: [{ label: 'Agentes de las partes', value: 'DbtrAgt (banco del que paga) y CdtrAgt (banco del que cobra).' }, { label: 'Agentes del tramo', value: 'InstgAgt (quien instruye) e InstdAgt (quien recibe la instrucción) en cada mensaje.' }, { label: 'Intermediarios', value: 'Puede haber agentes intermedios entre ambos bancos.' }],
    analogy: { text: 'Como los agentes de una mudanza: el dueño de los muebles es el cliente; las empresas que los transportan son los agentes.', limit: 'Un mismo banco puede ocupar varios roles de agente a la vez.' },
    example: { title: 'Mismo banco, varios roles', text: 'BANK_A es DbtrAgt (banco de CUSTOMER_A) y también InstgAgt (quien envía la instrucción).', outcome: 'Los campos son distintos aunque el BIC sea el mismo.' },
    diagram: seq('Partes y agentes', p2p, [
      [0, 1, 'Parte → su agente', 'CUSTOMER_A (Dbtr) pide el pago a BANK_A (DbtrAgt).', 'debtor'],
      [1, 2, 'InstgAgt → siguiente', 'En este tramo BANK_A es el agente instructor.'],
      [2, 3, 'Hacia el CdtrAgt', 'La instrucción llega a BANK_B, agente del acreedor.', 'creditor-agent'],
      [3, 4, 'Agente → su parte', 'BANK_B abona a CUSTOMER_B (Cdtr).'],
    ]),
    related: ['actors', 'debtor-agent', 'creditor-agent', 'participant'],
  },
  {
    id: 'debtor', title: 'Deudor', subtitle: 'Dbtr · quien paga',
    summary: 'La parte que debe el importe y cuya cuenta se debita en una transferencia de crédito.',
    plain: 'Es quien paga: la persona o empresa de la que sale el dinero.',
    aliases: ['Dbtr', 'debtor', 'pagador', 'ordenante'],
    facts: [{ label: 'En el XML', value: 'Bloque Dbtr, con su cuenta en DbtrAcct.' }, { label: 'No confundir', value: 'Su banco es el DbtrAgt; el deudor es el cliente.' }],
    analogy: { text: 'Quien paga la cuenta del restaurante, no el datáfono con el que paga.', limit: 'En algunos pagos alguien paga en nombre del deudor (Ultimate Debtor).' },
    example: { title: 'En la muestra', text: 'CUSTOMER_A es el Dbtr y su cuenta es DEMO-ORIGIN-ACCOUNT-1001.', outcome: 'BANK_A, su banco, aparece como DbtrAgt.' },
    diagram: seq('El deudor inicia', p2p, [[0, 1, 'Ordena pagar', 'CUSTOMER_A pide a su banco transferir.'], [1, 0, 'Débito', 'BANK_A descuenta el importe de su cuenta (según el modelo, al instante o reservado).']]),
    related: ['creditor', 'debtor-agent', 'actors'], xml: true, xmlFocus: 'actors',
  },
  {
    id: 'creditor', title: 'Acreedor', subtitle: 'Cdtr · quien cobra',
    summary: 'La parte a la que se debe el importe y cuya cuenta se acredita en una transferencia de crédito.',
    plain: 'Es quien cobra: la persona o empresa a la que llega el dinero.',
    aliases: ['Cdtr', 'creditor', 'cobrador'],
    facts: [{ label: 'En el XML', value: 'Bloque Cdtr, con su cuenta en CdtrAcct.' }, { label: 'Ojo', value: 'Que aparezca en el mensaje no significa que ya recibió el dinero.' }],
    analogy: { text: 'El dueño de la tienda que recibe el pago, no el banco que le lleva la cuenta.', limit: 'El beneficiario final puede ser otro (Ultimate Creditor).' },
    example: { title: 'En la muestra', text: 'CUSTOMER_B es el Cdtr y su cuenta es DEMO-BENEFICIARY-ACCOUNT-2001.', outcome: 'BANK_B, su banco, aparece como CdtrAgt.' },
    diagram: seq('El acreedor recibe', p2p, [[2, 3, 'Pago entregado', 'El banco del acreedor recibe la instrucción.'], [3, 4, 'Abono', 'BANK_B acredita la cuenta de CUSTOMER_B.']]),
    related: ['debtor', 'creditor-agent', 'beneficiary'], xml: true, xmlFocus: 'actors',
  },
  {
    id: 'beneficiary', title: 'Beneficiario', subtitle: 'Quien recibe el pago',
    summary: 'Término de uso común para la persona o empresa que recibe los fondos; en ISO 20022 suele corresponder al acreedor (Cdtr).',
    plain: 'Es la palabra cotidiana para "quien recibe el dinero". En el XML lo buscas como Cdtr.',
    aliases: ['beneficiary', 'receptor', 'payee'],
    facts: [{ label: 'Equivalencia', value: 'Beneficiario ≈ Cdtr; banco del beneficiario ≈ CdtrAgt.' }, { label: 'Final', value: 'Si el dinero es para un tercero, puede indicarse un Ultimate Creditor.' }],
    analogy: { text: 'La persona a cuyo nombre está el paquete.', limit: 'El término "beneficiario" no es una etiqueta ISO.' },
    example: { title: 'Llegada', text: 'CUSTOMER_B ve el abono en su cuenta de BANK_B.', outcome: 'Para el cliente, ese abono es "el pago llegó"; antes podía estar en camino.' },
    diagram: seq('Hasta el beneficiario', p2p, [[1, 2, 'Instrucción', 'El pago sale del banco del pagador.'], [2, 3, 'Entrega', 'Llega al banco del beneficiario.'], [3, 4, 'Fondos disponibles', 'El beneficiario puede usar el dinero.']]),
    related: ['creditor', 'creditor-agent'],
  },
  {
    id: 'debtor-agent', title: 'Agente del deudor', subtitle: 'DbtrAgt · banco del que paga',
    summary: 'Institución que lleva la cuenta del deudor y desde la que se inicia el pago.',
    plain: 'Es el banco de quien paga. Recibe la orden de su cliente, la comprueba y la envía.',
    aliases: ['DbtrAgt', 'debtor agent', 'banco ordenante'],
    facts: [{ label: 'Responsabilidad', value: 'Autenticar al cliente, comprobar fondos y enviar la instrucción.' }, { label: 'En el XML', value: 'DbtrAgt/FinInstnId/BICFI.' }],
    analogy: { text: 'La oficina de correos donde dejas el paquete.', limit: 'El banco también responde por controles de fraude y cumplimiento.' },
    example: { title: 'BANK_A', text: 'CUSTOMER_A ordena el pago en su app; BANK_A valida su saldo.', outcome: 'BANK_A envía la instrucción como DbtrAgt.' },
    diagram: seq('El banco del pagador', p2p, [[0, 1, 'Orden', 'El cliente se autentica y ordena.'], [1, 0, 'Validación', 'BANK_A comprueba identidad, saldo y límites.'], [1, 2, 'Envío', 'Envía la instrucción al sistema.']]),
    related: ['debtor', 'agent', 'creditor-agent'], xml: true, xmlFocus: 'actors',
  },
  {
    id: 'creditor-agent', title: 'Agente del acreedor', subtitle: 'CdtrAgt · banco del que cobra',
    summary: 'Institución que lleva la cuenta del acreedor y que debe acreditar los fondos.',
    plain: 'Es el banco de quien cobra. Recibe la instrucción, comprueba la cuenta y abona a su cliente.',
    aliases: ['CdtrAgt', 'creditor agent', 'banco beneficiario'],
    facts: [{ label: 'Decide', value: 'Aceptar o rechazar (por ejemplo, si la cuenta no existe).' }, { label: 'En el XML', value: 'CdtrAgt/FinInstnId/BICFI.' }],
    analogy: { text: 'La oficina de correos del destino que entrega el paquete en la puerta.', limit: 'Debe cumplir los tiempos del esquema para responder y abonar.' },
    example: { title: 'Cuenta cerrada', text: 'BANK_B recibe un pago para una cuenta cerrada.', outcome: 'Lo rechaza; si ya se hubiese liquidado, tocaría una devolución.' },
    diagram: seq('El banco del beneficiario', p2p, [[2, 3, 'Instrucción', 'BANK_B recibe el pago.'], [3, 2, 'Acepta o rechaza', 'Comprueba la cuenta y responde.', 'pacs.002'], [3, 4, 'Abono', 'Si aceptó, acredita al cliente.']]),
    related: ['creditor', 'agent', 'debtor-agent'], xml: true, xmlFocus: 'actors',
  },

  // ── Identifiers ──────────────────────────────────────────────────────────
  {
    id: 'msgid', title: 'MsgId', subtitle: 'Identificador del mensaje',
    summary: 'Referencia que el emisor asigna a un mensaje concreto (GrpHdr/MsgId). Identifica el mensaje, no cada pago que contiene.',
    plain: 'Es el "número de envío". Si un mensaje lleva varios pagos, todos comparten el mismo MsgId pero cada uno tiene su propio TxId.',
    aliases: ['MsgId', 'message identification', 'GrpHdr/MsgId'],
    facts: [{ label: 'Quién lo asigna', value: 'La institución que crea el mensaje.' }, { label: 'Para qué sirve', value: 'Referirse al mensaje completo: por ejemplo, un pacs.002 puede decir "sobre el mensaje MSG-001".' }, { label: 'Vecinos', value: 'AppHdr/BizMsgIdr identifica el mensaje desde la cabecera; es otro campo.' }],
    analogy: { text: 'El número de guía de una caja que lleva varios paquetes.', limit: 'Cada paquete (transacción) necesita además su propia referencia.' },
    example: { title: 'En la muestra', text: 'MsgId = MSG-001, NbOfTxs = 1, TxId = TX-001.', outcome: 'Si el mensaje llevara 3 pagos, seguiría siendo MSG-001 con 3 TxId distintos.' },
    caution: 'Un MsgId repetido puede hacer que el receptor trate el mensaje como duplicado.',
    diagram: seq('Referirse al mensaje', banks, [[0, 1, 'pacs.008 · MSG-001', 'El mensaje lleva su identificador en GrpHdr.', 'pacs.008'], [1, 0, 'pacs.002 sobre MSG-001', 'El estado puede referirse al mensaje original por su MsgId.', 'pacs.002']]),
    related: ['identifiers', 'txid', 'bah', 'pacs.008'], xml: true, xmlFocus: 'group',
  },
  {
    id: 'endtoendid', title: 'EndToEndId', subtitle: 'La referencia del que inicia el pago',
    summary: 'Referencia asignada por la parte que inicia el pago, que debe viajar sin cambios a lo largo de toda la cadena hasta el beneficiario.',
    plain: 'Es la referencia "del cliente": la que pone quien ordena el pago (por ejemplo, el número de factura) y que debe llegar intacta al otro lado.',
    aliases: ['EndToEndId', 'end to end', 'E2E', 'referencia del cliente'],
    facts: [{ label: 'Dueño', value: 'El iniciador (el cliente o su sistema), no los bancos.' }, { label: 'Regla de oro', value: 'Ningún banco intermedio debe cambiarla.' }, { label: 'Sin referencia', value: 'Si no hay, se usa el valor convencional NOTPROVIDED.' }],
    analogy: { text: 'El número de pedido que escribes en el paquete: la empresa de transporte usa sus propios códigos, pero el destinatario reconoce tu número.', limit: 'Su formato y obligatoriedad dependen del esquema.' },
    example: { title: 'Factura', text: 'CUSTOMER_A paga la factura E2E-001. BANK_A asigna TX-001.', outcome: 'CUSTOMER_B concilia con E2E-001; los bancos se hablan con TX-001.' },
    diagram: seq('Una referencia que no cambia', p2p, [[0, 1, 'E2E-001', 'El cliente pone su referencia.'], [1, 2, 'E2E-001 + TX-001', 'El banco añade su TxId; no toca el EndToEndId.'], [2, 3, 'E2E-001 + TX-001', 'Viaja igual.'], [3, 4, 'E2E-001', 'El beneficiario la recibe para conciliar.', 'reconciliation']]),
    related: ['identifiers', 'txid', 'uetr', 'reconciliation'], xml: true, xmlFocus: 'ids',
  },
  {
    id: 'txid', title: 'TxId', subtitle: 'La referencia entre bancos',
    summary: 'Referencia que asigna el primer agente instructor a una transacción para identificarla en la cadena interbancaria.',
    plain: 'Es la referencia "de los bancos" para un pago concreto. Es la que se usa para preguntar por su estado, devolverlo o investigarlo.',
    aliases: ['TxId', 'transaction identification', 'referencia interbancaria'],
    facts: [{ label: 'Quién lo asigna', value: 'El primer banco que instruye el pago interbancario.' }, { label: 'Alcance', value: 'Una transacción, no el mensaje completo.' }, { label: 'Uso posterior', value: 'Estados (pacs.002), devoluciones (pacs.004) y consultas suelen citarlo como "Orgnl".' }],
    analogy: { text: 'El número de seguimiento que la empresa de transporte asigna a tu paquete.', limit: 'En algunos esquemas el sistema o el UETR asumen parte de ese papel.' },
    example: { title: 'Preguntar por un pago', text: 'BANK_A no recibe respuesta sobre TX-001.', outcome: 'Pide su estado citando OrgnlTxId = TX-001.' },
    diagram: seq('El TxId en el ciclo de vida', banks, [[0, 1, 'pacs.008 · TX-001', 'Se asigna al instruir.', 'pacs.008'], [1, 2, 'Entrega', 'El TxId viaja con la transacción.'], [2, 0, 'Estado · OrgnlTxId TX-001', 'Las respuestas lo citan como referencia original.', 'pacs.002']]),
    related: ['identifiers', 'endtoendid', 'msgid', 'uetr'], xml: true, xmlFocus: 'ids',
  },
  {
    id: 'uetr', title: 'UETR', subtitle: 'Referencia única universal',
    summary: 'Identificador único (formato UUID v4) que acompaña a una transacción de principio a fin para poder rastrearla en todos los bancos que toca.',
    plain: 'Es un código aleatorio largo que no se repite en ningún lugar del mundo. Si cada banco lo conserva, todos pueden seguir el mismo pago con el mismo número.',
    aliases: ['UETR', 'unique end-to-end transaction reference', 'UUID', 'tracking'],
    facts: [{ label: 'Formato', value: '36 caracteres en grupos 8-4-4-4-12, generado al azar.' }, { label: 'Diferencia con EndToEndId', value: 'EndToEndId lo elige el cliente y puede repetirse; UETR es único por diseño.' }, { label: 'Obligatoriedad', value: 'Depende de la versión del mensaje y del esquema.' }],
    analogy: { text: 'Como el número de serie de un billete: identifica ese billete y solo ese.', limit: 'Solo sirve si todos los que tocan el pago lo conservan.' },
    example: { title: 'Un pago con dos tramos', text: 'Un pago pasa por BANK_A, un intermediario y BANK_B con el UETR 4f5a…1904.', outcome: 'Los tres pueden consultar el estado con ese mismo valor.' },
    diagram: seq('El mismo UETR en cada tramo', { actors: ['BANK_A', 'INTERMEDIARIO', 'BANK_B'], roles: ['agent', 'agent', 'agent'] }, [[0, 1, 'UETR 4f5a…', 'Se genera al crear el pago.'], [1, 2, 'UETR 4f5a…', 'El intermediario lo conserva.'], [2, 0, 'Consulta por UETR', 'Cualquiera puede rastrear con el mismo valor.']]),
    related: ['identifiers', 'endtoendid', 'txid'], xml: true, xmlFocus: 'ids',
  },

  {
    id: 'currency-code', title: 'Código de moneda · XXX', subtitle: 'ISO 4217 · atributo Ccy',
    summary: 'Los importes en ISO 20022 indican su moneda con un código de tres letras de la norma ISO 4217, en el atributo Ccy. XXX es el código oficial para "sin moneda".',
    plain: 'Cuando ves "250 XXX" en esta aula, no es una moneda real: XXX significa "sin moneda". Lo usamos a propósito para que ningún ejemplo represente dinero de verdad. En un pago real verías USD, EUR, DOP, BBD, etc.',
    aliases: ['XXX', 'Ccy', 'ISO 4217', 'moneda', 'divisa', 'currency'],
    facts: [{ label: 'Formato', value: 'Tres letras: las dos primeras suelen ser el país y la tercera la moneda (DOP = peso dominicano, USD = dólar estadounidense).' }, { label: 'En el XML', value: 'Va como atributo del importe: <IntrBkSttlmAmt Ccy="XXX">250.00</IntrBkSttlmAmt>.' }, { label: 'XXX', value: 'Código ISO 4217 reservado para operaciones "sin moneda". Aquí marca que el ejemplo es sintético.' }],
    analogy: { text: 'Como usar "Fulano de Tal" en un formulario de ejemplo: el campo está bien escrito, pero no es una persona real.', limit: 'Un sistema de pagos real rechazaría XXX en una transferencia de dinero.' },
    example: { title: 'Mismo pago, moneda real', text: 'En el aula: 250.00 XXX. En un pago real en República Dominicana se vería, por ejemplo, Ccy="DOP".', outcome: 'La estructura del mensaje es la misma; solo cambia el código.' },
    diagram: seq('El importe viaja con su moneda', banks, [[0, 1, 'Importe + Ccy', 'El pacs.008 indica 250.00 con Ccy="XXX" en el ejemplo.', 'pacs.008'], [1, 2, 'Mismo importe y moneda', 'Cada banco lee el código para saber de qué moneda se trata.']]),
    related: ['pacs.008', 'xml-basics', 'settlement'], xml: true, xmlFocus: 'amount',
  },

  {
    id: 'iban', title: 'IBAN', subtitle: 'ISO 13616 · número de cuenta internacional',
    summary: 'International Bank Account Number: formato estándar (ISO 13616) para identificar una cuenta bancaria de forma única y verificable, con el país, unos dígitos de control y el número de cuenta nacional.',
    plain: 'Es el "número de cuenta con pasaporte": empieza por el país, lleva dos números que detectan errores de tecleo y luego la cuenta tal como la numera ese país. Identifica la cuenta; el banco lo identifica el BIC.',
    aliases: ['IBAN', 'ISO 13616', 'número de cuenta', 'cuenta internacional', 'account number', 'CdtrAcct', 'DbtrAcct'],
    facts: [
      { label: 'Estructura', value: '2 letras de país (ISO 3166) + 2 dígitos de control + el BBAN, el número de cuenta nacional. Cada país fija la longitud total: en República Dominicana son 28 caracteres.' },
      { label: 'Dígitos de control', value: 'Se calculan con un algoritmo módulo 97. Si alguien teclea mal un carácter, el IBAN deja de ser válido y el error se detecta antes de enviar el pago.' },
      { label: 'En el XML', value: 'Dentro de la cuenta (DbtrAcct, CdtrAcct…) hay una elección: <Id><IBAN>…</IBAN></Id> o, si no hay IBAN, <Id><Othr><Id>…</Id></Othr></Id>.' },
      { label: 'IBAN ≠ BIC', value: 'El IBAN dice qué cuenta; el BIC (BICFI) dice qué banco. Un pago suele llevar los dos.' },
    ],
    analogy: { text: 'Como una dirección postal completa con código postal: el país primero, luego un dato de control y después la dirección local. Si falta o sobra una cifra, se nota.', limit: 'Que un IBAN sea válido solo prueba que está bien escrito: no garantiza que la cuenta exista, esté abierta o sea del beneficiario.' },
    example: { title: 'Dos cuentas sintéticas', text: 'CUSTOMER_A: DO58 AAAA 0000 0000 0000 0000 1001 (en BANK_A). CUSTOMER_B: DO45 BBBB 0000 0000 0000 0000 2001 (en BANK_B).', outcome: 'Ambos pasan la verificación módulo 97. Si cambias una cifra, dejan de pasarla y el banco lo rechaza antes de enviarlo.' },
    caution: 'No todos los países usan IBAN (por ejemplo, Estados Unidos o Barbados no lo usan para sus cuentas nacionales). Por eso ISO 20022 permite Othr. El XML anotado de esta aula usa Othr; los Recorridos usan IBAN.',
    diagram: seq('El IBAN en un pago', p2p, [
      [0, 1, 'Ordena con el IBAN de B', 'CUSTOMER_A indica el IBAN del beneficiario.'],
      [1, 0, 'Valida el IBAN', 'BANK_A comprueba el formato y los dígitos de control (módulo 97). Si hay un error de tecleo, se lo indica al cliente antes de enviar nada.'],
      [1, 2, 'pacs.008 con CdtrAcct/IBAN', 'El IBAN viaja en la cuenta del acreedor; el BIC del banco va en CdtrAgt.', 'pacs.008'],
      [2, 3, 'Entrega', 'BANK_B busca la cuenta por el IBAN. Si no existe, rechaza (por ejemplo AC01).', 'reject'],
      [3, 4, 'Abono', 'El dinero llega a la cuenta identificada por el IBAN.'],
    ]),
    related: ['creditor', 'debtor', 'pacs.008', 'pain.001', 'currency-code'], xml: true, xmlFocus: 'actors',
  },

  // ── Lifecycle ────────────────────────────────────────────────────────────
  {
    id: 'instruction', title: 'Instrucción de pago', subtitle: 'La orden de mover dinero',
    summary: 'Orden, dada por un cliente a su banco o por un banco a otro, de transferir un importe a un beneficiario.',
    plain: 'Es el "por favor, paga esto". Puede ir del cliente al banco (iniciación) o de un banco a otro (interbancaria).',
    aliases: ['instruction', 'orden de pago', 'payment instruction'],
    facts: [{ label: 'Cliente → banco', value: 'En ISO 20022, la familia pain (por ejemplo pain.001).' }, { label: 'Banco → banco', value: 'La familia pacs (por ejemplo pacs.008).' }, { label: 'Ojo', value: 'Una instrucción es una petición: puede aceptarse, rechazarse o quedar pendiente.' }],
    analogy: { text: 'Una orden de compra: dice qué quieres, pero aún no es la entrega.', limit: 'Una instrucción también tiene consecuencias legales según las reglas.' },
    example: { title: 'Dos instrucciones', text: 'CUSTOMER_A instruye a BANK_A; luego BANK_A instruye a BANK_B.', outcome: 'Son dos instrucciones distintas, con mensajes y responsables distintos.' },
    diagram: seq('Instrucción tras instrucción', p2p, [[0, 1, 'Instrucción del cliente', 'Por ejemplo, un pain.001 o una orden en la app.', 'pain.001'], [1, 2, 'Instrucción interbancaria', 'Por ejemplo, un pacs.008.', 'pacs.008'], [2, 3, 'Entrega', 'Llega al banco del beneficiario.']]),
    related: ['message', 'pain.001', 'pacs.008', 'validation'],
  },
  {
    id: 'message', title: 'Mensaje financiero', subtitle: 'La instrucción puesta en formato',
    summary: 'Unidad de información estructurada que una institución envía a otra para instruir, informar o preguntar algo sobre un pago.',
    plain: 'Es "la carta" que se mandan los bancos. En ISO 20022 cada tipo de carta tiene un nombre (pacs.008, pacs.002…) y un formato fijo.',
    aliases: ['message', 'mensaje', 'mensaje ISO'],
    facts: [{ label: 'Tipos', value: 'Instruir (pacs.008), informar estado (pacs.002), devolver (pacs.004), reportar (camt.053), investigar (camt.029)…' }, { label: 'Partes', value: 'Normalmente una cabecera de negocio (AppHdr) y el documento (Document).' }],
    analogy: { text: 'Formularios oficiales: cada trámite tiene su formulario, con casillas fijas.', limit: 'El mensaje transmite información; el dinero se mueve por la liquidación.' },
    example: { title: 'Una conversación', text: 'BANK_A envía un pacs.008 y BANK_B responde con un pacs.002.', outcome: 'Dos mensajes forman una conversación sobre el mismo pago.' },
    diagram: seq('Una conversación entre bancos', banks, [[0, 1, 'Instruir · pacs.008', 'Primera carta: el pago.', 'pacs.008'], [1, 2, 'Entrega', 'El sistema la pasa a BANK_B.'], [2, 1, 'Informar · pacs.002', 'Segunda carta: el estado.', 'pacs.002']]),
    related: ['iso20022', 'bah', 'instruction'],
  },
  {
    id: 'validation', title: 'Validación', subtitle: 'Comprobar antes de procesar',
    summary: 'Conjunto de comprobaciones (de formato, de esquema y de negocio) que se aplican a un mensaje antes de aceptarlo.',
    plain: 'Es revisar que "la carta" esté bien escrita y tenga sentido: formato correcto, campos obligatorios, cuentas que existen, importes dentro de límites.',
    aliases: ['validation', 'validar', 'XSD', 'reglas de negocio'],
    facts: [{ label: '1 · Bien formado', value: '¿El XML se puede leer?' }, { label: '2 · Válido contra XSD', value: '¿Cumple la estructura de ISO 20022?' }, { label: '3 · Reglas del esquema', value: '¿Cumple lo que exige el esquema (versión, campos, códigos)?' }, { label: '4 · Negocio', value: '¿La cuenta existe, hay fondos, pasa los controles?' }],
    analogy: { text: 'Revisar un formulario: que sea legible, que esté completo y que los datos sean ciertos.', limit: 'Cada capa de validación la hace un actor distinto y en un momento distinto.' },
    example: { title: 'Válido pero rechazado', text: 'Un pacs.008 cumple el XSD pero la cuenta del beneficiario está cerrada.', outcome: 'Pasa las validaciones técnicas y falla la de negocio.' },
    diagram: seq('Capas de validación', banks, [[0, 1, 'Instrucción', 'El sistema valida formato y reglas del esquema.'], [1, 2, 'Entrega', 'BANK_B valida reglas de negocio (cuenta, controles).'], [2, 1, 'Resultado', 'Acepta o rechaza con un código de motivo.', 'reject']]),
    related: ['reject', 'payment-scheme', 'xml-basics'],
  },
  {
    id: 'reject', title: 'Rechazo', subtitle: 'El pago no se acepta',
    summary: 'Respuesta negativa a una instrucción antes de que el pago se haya liquidado: la instrucción no sigue adelante.',
    plain: 'Es un "no" temprano. El pago se para antes de que el dinero se mueva entre bancos, normalmente con un código que explica por qué.',
    aliases: ['reject', 'rechazado', 'RJCT'],
    facts: [{ label: 'Cuándo', value: 'Antes de la liquidación.' }, { label: 'Cómo se comunica', value: 'Típicamente con un estado de rechazo (por ejemplo pacs.002 con RJCT) y un código de motivo.' }, { label: 'Efecto', value: 'No hay que devolver nada: el dinero no se movió entre bancos.' }],
    analogy: { text: 'Que te devuelvan una carta sin abrir porque la dirección no existe.', limit: 'Si el cliente ya fue debitado o reservado, su banco debe deshacer ese movimiento interno.' },
    example: { title: 'Cuenta inexistente', text: 'BANK_B rechaza TX-001 porque la cuenta no existe.', outcome: 'BANK_A libera los fondos de CUSTOMER_A y le informa.' },
    caution: 'Rechazo ≠ devolución. El rechazo ocurre antes de liquidar; la devolución, después.',
    diagram: seq('Un rechazo', p2p, [[1, 2, 'Instrucción', 'BANK_A envía el pago.'], [2, 3, 'Entrega', 'Llega a BANK_B.'], [3, 2, 'Rechazo · RJCT', 'BANK_B no acepta, con motivo.', 'pacs.002'], [2, 1, 'Rechazo', 'Se informa al origen.'], [1, 0, 'Fondos liberados', 'BANK_A deshace la reserva o el débito.']]),
    related: ['return', 'pacs.002', 'validation'],
  },
  {
    id: 'return', title: 'Devolución', subtitle: 'Enviar de vuelta un pago ya liquidado',
    summary: 'Nuevo pago, en sentido contrario, que devuelve los fondos de una transferencia que ya se había liquidado pero no pudo completarse.',
    plain: 'Es un "no" tardío: el dinero ya había llegado al banco del beneficiario, así que hay que mandarlo de vuelta con otro pago.',
    aliases: ['return', 'devuelto', 'pacs.004'],
    facts: [{ label: 'Cuándo', value: 'Después de la liquidación interbancaria.' }, { label: 'Cómo', value: 'Con un mensaje de devolución (pacs.004) que referencia el pago original.' }, { label: 'Efecto', value: 'Es un nuevo movimiento de dinero de B hacia A.' }],
    analogy: { text: 'Como devolver un producto que ya pagaste: la tienda te hace un reembolso, no "despaga" la compra.', limit: 'Qué casos permiten devolución y en qué plazo depende del esquema.' },
    example: { title: 'Cuenta cerrada tras liquidar', text: 'El pago TX-001 se liquidó, pero BANK_B no puede abonarlo.', outcome: 'BANK_B envía un pacs.004 por 250 XXX citando TX-001.' },
    caution: 'Devolución ≠ cancelación. La cancelación es una petición; la devolución es el pago de vuelta.',
    diagram: seq('Una devolución', p2p, [[1, 2, 'Pago original', 'Se liquida entre bancos.', 'pacs.008'], [2, 3, 'Entrega', 'BANK_B recibe los fondos.'], [3, 2, 'Devolución · pacs.004', 'BANK_B no puede abonar y devuelve.', 'pacs.004'], [2, 1, 'Fondos de vuelta', 'BANK_A recibe la devolución.'], [1, 0, 'Abono al pagador', 'CUSTOMER_A recupera su dinero.']]),
    related: ['reject', 'pacs.004', 'recall', 'reversal'],
  },
  {
    id: 'recall', title: 'Solicitud de cancelación (recall)', subtitle: 'Pedir que se devuelva un pago',
    summary: 'Petición del banco del pagador para que se cancele o devuelva un pago ya enviado, por error, duplicado o sospecha de fraude.',
    plain: 'Es pedir "por favor, devuélveme ese pago". El otro banco puede aceptar (y devolver) o negarse.',
    aliases: ['recall', 'cancellation request', 'camt.056', 'cancelación'],
    facts: [{ label: 'Mensaje típico', value: 'camt.056 para pedir y camt.029 para responder.' }, { label: 'Resultado', value: 'Si se acepta, los fondos vuelven con una devolución (pacs.004).' }, { label: 'No es automático', value: 'El banco receptor (y a veces el beneficiario) debe estar de acuerdo.' }],
    analogy: { text: 'Pedirle a alguien que te devuelva un dinero que le enviaste por error: puede decir que sí o que no.', limit: 'Plazos, motivos y obligaciones los fija el esquema.' },
    example: { title: 'Pago duplicado', text: 'BANK_A envió dos veces TX-001.', outcome: 'Pide con camt.056 la cancelación del duplicado y espera la respuesta.' },
    diagram: seq('Un recall', banks, [[0, 1, 'Petición · camt.056', 'BANK_A pide cancelar el pago.', 'camt.056'], [1, 2, 'Entrega', 'BANK_B evalúa (y puede consultar al cliente).'], [2, 1, 'Respuesta · camt.029', 'Acepta o rechaza la petición.', 'camt.029'], [2, 0, 'Si acepta · pacs.004', 'Los fondos vuelven en una devolución.', 'pacs.004']]),
    related: ['camt.056', 'camt.029', 'return', 'reversal'],
  },
  {
    id: 'reversal', title: 'Reversión', subtitle: 'Anular un pago por quien lo envió',
    summary: 'Operación iniciada por quien envió un pago para anular sus efectos, normalmente por un error del propio emisor, cuando las reglas lo permiten.',
    plain: 'Es "deshacer mi propio error", hecho por quien envió el pago. Es menos común en pagos inmediatos que la devolución o el recall.',
    aliases: ['reversal', 'revertir', 'anulación'],
    facts: [{ label: 'Quién la inicia', value: 'El emisor original (no el receptor).' }, { label: 'Disponibilidad', value: 'Muchos esquemas de pagos inmediatos no la permiten y usan recall + devolución.' }],
    analogy: { text: 'Como un vendedor que anula un cobro duplicado con su propio datáfono.', limit: 'Su uso exacto varía mucho entre esquemas.' },
    example: { title: 'Error del emisor', text: 'Un sistema de BANK_A envió dos veces el mismo débito.', outcome: 'Si el esquema lo permite, BANK_A revierte el duplicado.' },
    caution: 'Reversión, devolución y recall no son sinónimos: cambia quién inicia y en qué momento.',
    diagram: seq('Una reversión', banks, [[0, 1, 'Pago (duplicado)', 'Se envía por error.'], [1, 2, 'Entrega', 'BANK_B lo recibe.'], [0, 1, 'Reversión', 'El emisor anula su propio error, si las reglas lo permiten.'], [1, 2, 'Anulación', 'Se compensa el efecto del pago original.']]),
    related: ['recall', 'return', 'reject'],
  },
  {
    id: 'investigation', title: 'Investigación', subtitle: 'Averiguar qué pasó con un pago',
    summary: 'Proceso formal para consultar, reclamar o aclarar un pago cuyo resultado no está claro o es incorrecto.',
    plain: 'Es "abrir un caso": algo no cuadra con un pago y un banco le pregunta al otro qué pasó, siguiendo un procedimiento.',
    aliases: ['investigation', 'caso', 'case', 'reclamo'],
    facts: [{ label: 'Cuándo', value: 'Pago que no llega, importe incorrecto, sospecha de duplicado o fraude.' }, { label: 'Mensajes típicos', value: 'Familia camt de excepciones e investigaciones (por ejemplo camt.056, camt.029).' }, { label: 'Clave', value: 'Las referencias originales (TxId, UETR) para identificar el pago.' }],
    analogy: { text: 'Abrir un reclamo con número de caso en una empresa de transporte.', limit: 'Cada esquema define plazos y formatos de las investigaciones.' },
    example: { title: 'Cliente que no recibe', text: 'CUSTOMER_B dice que no recibió el pago E2E-001.', outcome: 'BANK_A abre un caso con la referencia y espera la resolución.' },
    diagram: seq('Un caso de investigación', p2p, [[4, 3, 'Reclamo', 'El cliente avisa que no ve el dinero.'], [3, 1, 'Consulta / caso', 'Los bancos se preguntan con las referencias originales.'], [1, 3, 'Resolución · camt.029', 'Se informa el resultado del caso.', 'camt.029']]),
    related: ['camt.029', 'reconciliation', 'timeouts'],
  },
  {
    id: 'reconciliation', title: 'Conciliación', subtitle: 'Que los registros cuadren',
    summary: 'Comparar los pagos esperados o enviados con los movimientos reales de la cuenta para confirmar que todo coincide y detectar diferencias.',
    plain: 'Es "cuadrar las cuentas": revisar que cada pago que esperabas aparezca en tu extracto con el importe y la referencia correctos.',
    aliases: ['reconciliation', 'conciliar', 'cuadre'],
    facts: [{ label: 'Insumos', value: 'Tus registros y los reportes del banco (por ejemplo camt.053 o camt.054).' }, { label: 'Herramienta clave', value: 'Las referencias: EndToEndId, información de remesa, importes.' }, { label: 'Diferencias', value: 'Lo que no cuadra se investiga.' }],
    analogy: { text: 'Revisar el extracto de tu tarjeta contra tus recibos.', limit: 'En empresas se hace a gran escala y de forma automática.' },
    example: { title: 'Factura cobrada', text: 'CUSTOMER_B esperaba E2E-001 por 250 XXX.', outcome: 'Lo encuentra en su camt.053 y marca la factura como pagada.' },
    diagram: seq('Cuadrar con el extracto', { actors: ['CUSTOMER_B', 'BANK_B'], roles: ['party', 'agent'] }, [[1, 0, 'Aviso · camt.054', 'El banco notifica el abono.', 'camt.054'], [1, 0, 'Extracto · camt.053', 'Al cierre, el extracto lista los movimientos.', 'camt.053'], [0, 1, 'Consulta si no cuadra', 'Las diferencias se investigan.', 'investigation']]),
    related: ['camt.053', 'camt.054', 'endtoendid', 'investigation'],
  },
  {
    id: 'cash-management', title: 'Gestión de efectivo', subtitle: 'camt · reportes y consultas',
    summary: 'Área de ISO 20022 (mensajes camt) para informar saldos y movimientos, consultar cuentas y gestionar excepciones e investigaciones.',
    plain: 'Son los mensajes que no mueven dinero sino que cuentan qué pasó: extractos, avisos, consultas y respuestas a reclamos.',
    aliases: ['cash management', 'camt', 'reportes'],
    facts: [{ label: 'Reportes', value: 'camt.053 (extracto), camt.054 (avisos de movimiento).' }, { label: 'Consultas', value: 'camt.003 / camt.004 (información de cuenta).' }, { label: 'Excepciones', value: 'camt.056 (petición de cancelación), camt.029 (resolución).' }],
    analogy: { text: 'El área de "atención y reportes" de un banco, no la caja.', limit: 'Cada esquema usa solo una parte de estos mensajes.' },
    example: { title: 'Fin del día', text: 'BANK_B envía a CUSTOMER_B un camt.053 con todos sus movimientos.', outcome: 'CUSTOMER_B concilia con ese extracto.' },
    diagram: seq('Mensajes que informan', { actors: ['CUSTOMER_B', 'BANK_B'], roles: ['party', 'agent'] }, [[1, 0, 'camt.054 · aviso', 'Movimiento individual.', 'camt.054'], [0, 1, 'camt.003 · consulta', 'Pide información de cuenta.', 'camt.003'], [1, 0, 'camt.004 · respuesta', 'Devuelve la información.', 'camt.004'], [1, 0, 'camt.053 · extracto', 'Resumen del periodo.', 'camt.053']]),
    related: ['camt.053', 'camt.054', 'reconciliation', 'iso20022'],
  },
]
