export const confusionsEs: Record<string, { title: string; explanation: string }> = {
  'clearing-settlement': { title: 'Clearing vs. Settlement', explanation: 'Clearing determina quién le debe qué a quién. Settlement es la liquidación real de esa obligación. Un pago puede estar "cleared" sin haber sido aún "settled".' },
  'reject-return': { title: 'Reject vs. Return', explanation: 'Un reject significa que el pago nunca progresó más allá de la validación/aceptación. Un return significa que sí progresó, y ahora se está enviando de vuelta después de los hechos.' },
  'debtor-debtor-agent': { title: 'Debtor vs. Debtor Agent', explanation: 'El Debtor es la parte que debe/envía los fondos. El Debtor Agent es la institución que da servicio a esa parte. No son intercambiables.' },
  'message-transaction': { title: 'Mensaje vs. Transacción', explanation: 'Un solo mensaje (por ejemplo, una instancia de pacs.008) puede llevar múltiples transacciones individuales. Los identificadores a nivel de mensaje y a nivel de transacción responden preguntas diferentes.' },
  'msgid-txid': { title: 'MsgId vs. TxId', explanation: 'MsgId identifica el sobre del mensaje. TxId identifica una transacción específica dentro de él, que puede ser una de varias.' },
  'iso-scheme': { title: 'Requisito ISO vs. Requisito del Scheme', explanation: 'ISO 20022 define el modelo semántico/de mensaje, a menudo con elementos opcionales. Un scheme de pago específico puede requerir un elemento que ISO deja opcional. El cumplimiento del scheme, no solo del estándar base, determina qué es realmente obligatorio en ese contexto.' },
  'valid-xml-valid-payment': { title: 'XML Válido vs. Pago Válido', explanation: 'Un mensaje puede ser sintácticamente válido y válido contra el esquema, y aun así fallar en reglas de negocio, reglas del scheme, o simplemente no representar un pago que pueda completarse realmente.' },
  'pain001-pacs008': { title: 'pain.001 vs. pacs.008', explanation: 'pain.001 es un mensaje de iniciación de cliente a institución. pacs.008 es una transferencia de crédito interbancaria entre instituciones. Sirven a etapas distintas de un mismo proceso más amplio.' },
  'pacs004-camt004': { title: 'pacs.004 vs. camt.004', explanation: 'pacs.004 es PaymentReturn: devuelve un pago que ya progresó. camt.004 es ReturnAccount: devuelve información de cuenta o balance, comúnmente después de camt.003 GetAccount. Mismo número, familia distinta, significado de negocio distinto.' },
  'status-settlement': { title: 'Status vs. Settlement', explanation: 'Un estado reportado (por ejemplo, "accepted") te dice que se tomó una decisión sobre el pago. No confirma por sí mismo que el valor realmente se haya liquidado.' },
  'initiation-movement': { title: 'Iniciación de pago vs. movimiento de fondos', explanation: 'Iniciar un pago crea una instrucción. El movimiento real de los fondos ocurre después, en el settlement/crédito. Ambos pueden estar separados en el tiempo.' },
}
