export interface GlossaryTranslation {
  oneLine: string
  fullExplanation: string
  commonConfusion?: string
}

export const glossaryEs: Record<string, GlossaryTranslation> = {
  ach: { oneLine: 'Un sistema de clearing de pagos por lotes, típicamente no en tiempo real.', fullExplanation: 'Los sistemas ACH (Automated Clearing House) procesan pagos en lotes a intervalos programados en vez de continuamente en tiempo real. Se usan comúnmente para pagos de menor valor y no urgentes, como nómina o pago de facturas.' },
  agent: { oneLine: 'Una institución financiera que da servicio a una parte en un pago.', fullExplanation: 'Un agente (por ejemplo, Debtor Agent, Creditor Agent) es la institución que actúa en nombre de, o da servicio a la cuenta de, una parte como un Debtor o Creditor. Los agentes no son las partes mismas.', commonConfusion: 'No confundas un agente con la parte a la que da servicio.' },
  beneficiary: { oneLine: 'La parte que se pretende reciba finalmente los fondos.', fullExplanation: 'A menudo usado indistintamente con Creditor en el lenguaje cotidiano, aunque los mensajes ISO 20022 distinguen formalmente entre Creditor y Ultimate Creditor según el escenario.' },
  clearing: { oneLine: 'Determinar quién le debe qué a quién.', fullExplanation: 'Clearing es el proceso de intercambiar y validar instrucciones de pago y calcular las obligaciones resultantes entre participantes, antes de que ocurra cualquier transferencia final de valor.' },
  'clearing-system': { oneLine: 'Infraestructura que procesa y valida instrucciones de pago entre participantes.', fullExplanation: 'Un sistema de clearing intercambia instrucciones entre participantes y determina las obligaciones resultantes. No representa por sí mismo una parte o agente dueño de fondos.' },
  creditor: { oneLine: 'La parte que recibe los fondos.', fullExplanation: 'El Creditor es la parte a la que se le deben y finalmente se le pagan los fondos en una transferencia de crédito.' },
  'creditor-agent': { oneLine: 'La institución que da servicio al Creditor.', fullExplanation: 'Usualmente la institución financiera donde el Creditor tiene la cuenta que se acreditará.', commonConfusion: 'Creditor = recibe los fondos. Creditor Agent = institución que da servicio a esa parte.' },
  debtor: { oneLine: 'La parte que debe / envía los fondos.', fullExplanation: 'El Debtor es la parte cuya cuenta se debita para fondear una transferencia de crédito.' },
  'debtor-agent': { oneLine: 'La institución que da servicio al Debtor.', fullExplanation: 'Usualmente la institución financiera donde el Debtor tiene la cuenta que se debitará.', commonConfusion: 'Debtor = debe/envía los fondos. Debtor Agent = institución que da servicio a esa parte.' },
  endtoendid: { oneLine: 'Una referencia pensada para viajar sin cambios con el pago de extremo a extremo.', fullExplanation: 'Asignada típicamente por el lado del deudor original y pensada para permanecer sin cambios mientras el pago se mueve entre instituciones, lo que la hace valiosa para el rastreo, la investigación y la reconciliación.' },
  'fast-payment': { oneLine: 'Un pago procesado casi en tiempo real, a menudo disponible 24/7.', fullExplanation: 'Los sistemas de pagos instantáneos (fast/instant) procesan pagos en segundos y suelen estar disponibles todo el día. Las garantías específicas dependen del esquema.' },
  finality: { oneLine: 'El punto en el que un pago se considera irrevocable.', fullExplanation: 'Finality describe cuándo un pago ya no puede revertirse mediante una simple cancelación. Muchos esquemas de pagos instantáneos están diseñados para alta finalidad poco después de la confirmación.' },
  'gross-settlement': { oneLine: 'Cada obligación se liquida individualmente y en su totalidad.', fullExplanation: 'A diferencia del net settlement, donde las obligaciones se compensan entre sí antes de liquidarse. Los sistemas de liquidación bruta en tiempo real (RTGS) liquidan las transacciones individualmente conforme ocurren.' },
  instruction: { oneLine: 'Una directiva para mover fondos, distinta de que los fondos realmente se muevan.', fullExplanation: 'Una instrucción de pago representa la intención/orden de pagar. La liquidación real de la obligación ocurre en el settlement, que puede darse en un momento distinto.' },
  message: { oneLine: 'Una comunicación estructurada intercambiada entre participantes de pagos.', fullExplanation: 'Un mensaje ISO 20022 es una instancia de una definición de mensaje (por ejemplo, pacs.008) usada para comunicar información de negocio entre participantes. Un solo mensaje puede llevar múltiples transacciones.' },
  msgid: { oneLine: 'Identifica el sobre del mensaje, no una transacción individual.', fullExplanation: 'Message Identification es asignado por el emisor para identificar el mensaje en su totalidad. Un mensaje puede llevar muchas transacciones, cada una con sus propios identificadores.', commonConfusion: 'MsgId identifica el sobre; no identifica un solo pago cuando el mensaje lleva múltiples transacciones.' },
  'net-settlement': { oneLine: 'Las obligaciones se compensan y solo se liquida la diferencia neta.', fullExplanation: 'En vez de liquidar cada obligación individualmente, el net settlement calcula la posición neta entre participantes y liquida solo esa diferencia.' },
  participant: { oneLine: 'Una entidad conectada y autorizada para usar un sistema de pagos.', fullExplanation: 'Los participantes (típicamente instituciones financieras) están conectados a una infraestructura de clearing/settlement y siguen sus reglas para enviar y recibir pagos.' },
  'payment-rail': { oneLine: 'La infraestructura subyacente que mueve instrucciones de pago y valor.', fullExplanation: 'Ejemplo: un sistema de pagos instantáneos, un sistema RTGS, una red de tarjetas. El rail es la "tubería"; el scheme es el reglamento para usarla.' },
  'payment-scheme': { oneLine: 'Las reglas, roles y obligaciones que los participantes acuerdan al usar un rail.', fullExplanation: 'Define reglas de uso de mensajes, tiempos, responsabilidad y otros requisitos operativos para un payment rail dado.' },
  recall: { oneLine: 'Una solicitud de recuperar un pago ya enviado, distinta de una devolución.', fullExplanation: 'Un recall es iniciado por el lado emisor solicitando que un pago sea recuperado, generalmente antes o poco después de la aceptación, y su resultado no está garantizado. Esto difiere de un return, que representa fondos enviados de vuelta después de que el pago ya fue procesado.', commonConfusion: 'Las solicitudes de cancelación/recall no son lo mismo que una devolución — una devolución implica que el pago ya progresó y los fondos se están enviando de vuelta; un recall es una solicitud que puede o no ser honrada.' },
  reconciliation: { oneLine: 'Comparar registros entre sistemas o instituciones para confirmar que coinciden.', fullExplanation: 'La reconciliación usa identificadores (como EndToEndId) y estados reportados para confirmar que el estado de un pago es consistente entre los sistemas e instituciones involucrados.' },
  reject: { oneLine: 'Una instrucción de pago no es aceptada antes/durante la validación.', fullExplanation: 'Un reject significa que el pago no progresó más allá de la validación/aceptación — nunca se convirtió en un pago liquidado o acreditado.', commonConfusion: 'Reject vs. Return — ver la lección dedicada.' },
  return: { oneLine: 'Un pago previamente aceptado se envía de vuelta después.', fullExplanation: 'Un return significa que el pago ya había progresado (por ejemplo, fue aceptado o liquidado), pero después no pudo completarse, así que los fondos/el pago se envían de vuelta al lado original.' },
  rtgs: { oneLine: 'Real-Time Gross Settlement — liquida transacciones individual y continuamente.', fullExplanation: 'Un sistema RTGS liquida cada pago individualmente y en tiempo real, típicamente usado para pagos de alto valor o críticos en tiempo, a menudo operado por un banco central.' },
  settlement: { oneLine: 'La liquidación real de una obligación financiera.', fullExplanation: 'Settlement es cuando el valor realmente se mueve entre instituciones, dándole finalidad al pago. Es distinto de clearing, que solo determina la obligación.' },
  'settlement-account': { oneLine: 'Una cuenta usada para liquidar realmente las obligaciones de settlement.', fullExplanation: 'A menudo mantenida en un banco central o agente de settlement designado, usada específicamente para el movimiento de valor durante el settlement.' },
  txid: { oneLine: 'Identifica una transacción individual, a menudo dentro de la cadena de clearing/settlement.', fullExplanation: 'Transaction Identification se asigna a una transacción específica, que puede diferir del EndToEndId que viaja con el pago de extremo a extremo.' },
  uetr: { oneLine: 'Una referencia universal de transacción de extremo a extremo usada en algunas redes de pago.', fullExplanation: 'Cuando aplica, un UETR es una referencia única generada para una transacción que permite rastrearla a través de las entidades involucradas en su procesamiento. Su uso y formato dependen de la red/esquema específico.' },
  validation: { oneLine: 'Verificar que un mensaje o instrucción cumple las reglas requeridas antes de continuar.', fullExplanation: 'La validación puede ocurrir en varias capas — sintaxis, esquema, reglas de negocio y reglas específicas del esquema — y fallar en cualquiera de ellas puede impedir que un pago progrese.' },
}
