import type { FieldNote } from '@/content/reference/xmlGuide'

// English annotations for the synthetic pacs.008.001.10 study sample.
// Concept links are taken from the Spanish source (same ids).
export const fieldNotesEn: Record<string, Omit<FieldNote, 'concept'>> = {
  DataPDU: { name: 'Protocol Data Unit · transport container', meaning: 'Technical envelope that wraps the header and the business message into one delivery.', explain: 'PDU stands for “Protocol Data Unit”: the unit of data that travels over a messaging channel. DataPDU is this example’s outer box: inside it carries the business header (AppHdr) and the payment (Document). Some messaging platforms use envelopes with similar names; this one is fictitious and exists only to show there is a transport layer around the ISO message.', equivalent: 'A transport package starts here. What matters for the business is inside.', note: 'It is not part of ISO 20022 or pacs.008. Change the channel and this envelope changes; the pacs.008 inside does not.' },
  Body: { name: 'Container body', meaning: 'Holds AppHdr and Document inside the example envelope.', explain: 'The compartment of the envelope where the header and the message are placed together. Whether it exists, and its name, are decided by the transport format, not by ISO 20022.', equivalent: 'This package holds two pieces: the shipping label (AppHdr) and the letter (Document).', note: 'Not a mandatory ISO field. Another channel could carry AppHdr and Document differently.' },
  AppHdr: { name: 'Business Application Header (BAH)', meaning: 'Identifies who sends the message, to whom, and which kind of message it carries.', explain: 'A separate ISO 20022 header (head.001) that travels next to the payment message. It works like a shipping label: where it comes from, where it goes, what it contains and under which service it is exchanged, without repeating the payment details.', equivalent: 'This message is sent by AAAADODX to CCCCDODX, it is a pacs.008.001.10 and it is identified as MSG-001.', note: 'It has its own schema (head.001.001.02) and its own namespace. It is not part of the pacs.008 XSD.' },
  Fr: { name: 'From · sender', meaning: 'Who sends this business message.', explain: 'The messaging endpoint that created and sent the message. It is information about the delivery, not about who pays.', equivalent: 'This message comes from institution AAAADODX.', note: 'It is not the paying customer (Dbtr). It can coincide with an agent of the payment, but they are different roles.' },
  To: { name: 'To · receiver', meaning: 'Who this business message is addressed to.', explain: 'The messaging endpoint that must receive the message. In many flows it can be an infrastructure or a participant; the scheme defines it.', equivalent: 'This message is addressed to CCCCDODX.', note: 'Here To (CCCCDODX) differs from InstdAgt (BBBBDODX): the header says who gets the message; InstdAgt says who gets the payment instruction.' },
  FIId: { name: 'Financial Institution Identification', meaning: 'States that the header party is a financial institution.', explain: 'A choice inside Fr or To: the sender or receiver can be described in several ways, and FIId says “it is a financial institution”.', note: 'A container block; the actual code is further down, in FinInstnId/BICFI.' },
  FinInstnId: { name: 'Financial Institution Identification', meaning: 'Groups the data identifying a financial institution.', explain: 'This same block appears in many places (header, payment agents). What changes is the role containing it: InstgAgt, DbtrAgt, CdtrAgt, etc.', note: 'To know which institution it refers to, look at the parent block in the path, not just this name.' },
  BICFI: { name: 'Financial institution BIC', meaning: 'BIC code identifying a financial institution in this role.', explain: 'The BIC (Business Identifier Code, ISO 9362) is an 8- or 11-character code identifying an institution. It is its international “short name”.', parts: [{ label: 'AAAA', text: 'Institution code (4 letters).' }, { label: 'DO', text: 'Country, as an ISO 3166 code (DO = Dominican Republic).' }, { label: 'DX', text: 'Location code.' }, { label: '(XXX)', text: 'Branch, optional. If absent, the head office is meant.' }], note: 'The BICs in this sample are fictitious: AAAADODX = BANK_A, BBBBDODX = BANK_B, CCCCDODX = header receiver.' },
  BizMsgIdr: { name: 'Business Message Identifier', meaning: 'Reference identifying the business message from the header.', explain: 'The sender assigns this reference to identify the whole message (header + document) in its exchange.', equivalent: 'This delivery is called MSG-001.', note: 'In the sample it has the same value as GrpHdr/MsgId as a teaching choice, but they are different fields in different layers.' },
  MsgDefIdr: { name: 'Message Definition Identifier', meaning: 'Says which type and version of message is in Document.', explain: 'Before reading the document, the receiver knows from the header which ISO definition to apply.', parts: [{ label: 'pacs', text: 'Business area: Payments Clearing and Settlement (between institutions).' }, { label: '008', text: 'Message number: customer credit transfer.' }, { label: '001', text: 'Variant. 001 is ISO’s general variant.' }, { label: '10', text: 'Message version. Each version can change fields and rules.' }], equivalent: 'What is inside is a pacs.008 credit transfer, version 10.', note: 'It must match the Document namespace. A payment scheme may require a version other than the latest.' },
  BizSvc: { name: 'Business Service', meaning: 'Business service or agreement under which the message is exchanged.', explain: 'States which service’s rules apply to this message (for example, a specific instant payment service). The value is defined by the community using the service.', equivalent: 'This message follows the rules of service “example.ips.01”.', note: 'example.ips.01 is fictitious. ISO defines the field, but not the meaning of each value.' },
  CreDt: { name: 'Creation Date', meaning: 'Date and time the business message was created.', parts: [{ label: '2026-10-02', text: 'Date as year-month-day.' }, { label: 'T16:00:01', text: 'Time (T separates date and time).' }, { label: 'Z', text: 'UTC time zone (“Zulu”).' }], note: 'It is when the message was created, not when the money was settled.' },
  Document: { name: 'ISO 20022 document', meaning: 'Root of the pacs.008 payment message.', explain: 'Everything inside Document is the ISO 20022 message itself. Its namespace says exactly which definition and version to read it with.', equivalent: 'The pacs.008.001.10 starts here: the business content of the payment.', note: 'AppHdr and Document are siblings: the header is not inside the document.' },
  FIToFICstmrCdtTrf: { name: 'FI To FI Customer Credit Transfer', meaning: 'The customer credit transfer message between institutions.', explain: 'The main block of the pacs.008: one financial institution passes another the order to move money from one customer to another. It holds a common header (GrpHdr) and one or more transactions (CdtTrfTxInf).', equivalent: 'BANK_A instructs BANK_B a transfer on behalf of a customer.', note: 'The message carries an instruction. Its existence does not prove the money was already settled or credited.' },
  GrpHdr: { name: 'Group Header', meaning: 'Data common to all transactions in the message.', explain: 'Works like the message’s cover page: its identifier, when it was created, how many transactions it carries and how they are settled.', note: 'It separates the message identity (MsgId) from each payment’s identity (PmtId).' },
  MsgId: { name: 'Message Identification', meaning: 'Identifier the sender assigns to this pacs.008 message.', explain: 'Used to refer to the whole message, for example when a status (pacs.002) arrives about “message MSG-001”.', equivalent: 'This pacs.008 is called MSG-001.', note: 'It does not identify a transaction. A message can carry several, each with its own TxId.' },
  CreDtTm: { name: 'Creation Date Time', meaning: 'Date and time the pacs.008 message was created.', note: 'Different from AppHdr/CreDt even though they match in the sample: one dates the header and the other the document.' },
  NbOfTxs: { name: 'Number Of Transactions', meaning: 'How many transactions the message carries.', explain: 'Lets you check the message is complete: it must match the number of CdtTrfTxInf blocks.', equivalent: 'This message holds a single transfer.', note: 'Many instant payment schemes require 1, but it is not a universal ISO limit.' },
  SttlmInf: { name: 'Settlement Information', meaning: 'How the instruction should be settled between institutions.', note: 'It describes what is planned; it does not confirm settlement happened.' },
  SttlmMtd: { name: 'Settlement Method', meaning: 'Planned settlement method.', explain: 'Says through which route the obligation between the institutions will be settled.', parts: [{ label: 'CLRG', text: 'Through a clearing system (this sample’s value).' }, { label: 'INDA / INGA', text: 'On the books of the instructed or instructing agent.' }, { label: 'COVE', text: 'Through a separate cover payment.' }], equivalent: 'This payment will be settled through a clearing system.', note: 'It does not name the system nor prove settlement finished.' },
  CdtTrfTxInf: { name: 'Credit Transfer Transaction Information', meaning: 'All the data of one transfer: references, amount, parties, agents and remittance.', explain: 'It is “the payment” inside the message. If GrpHdr is the cover page, each CdtTrfTxInf is a specific transfer: who pays, whom, how much and with which references.', note: 'This is the transaction level. Data here applies to this transfer, not to the whole message.' },
  PmtId: { name: 'Payment Identification', meaning: 'The references used to identify and track this transfer.', explain: 'Groups several identifiers with different owners and scopes: the customer’s (EndToEndId), the bank’s (TxId) and the unique tracking one (UETR).', note: 'Do not swap them because they look alike: each answers a different question.' },
  EndToEndId: { name: 'End To End Identification', meaning: 'Reference set by whoever starts the payment, which must travel unchanged to the end.', explain: 'The “customer’s” reference: assigned by the party ordering the payment and kept along the whole chain, so payee and payer can recognise it.', equivalent: 'Whoever ordered the payment gave no reference of their own.', note: 'NOTPROVIDED is the conventional value when no reference was given: it is useless for tracking. Whether a scheme allows it depends on its rules.' },
  TxId: { name: 'Transaction Identification', meaning: 'Reference the first instructing bank assigns to the transaction in the interbank chain.', explain: 'The “banks’” reference: identifies this transaction between institutions and is the one usually quoted in statuses, returns and investigations.', equivalent: 'Between banks, this payment is known as TX-001.', note: 'It does not identify the message (that is MsgId) nor the customer’s order (that is EndToEndId).' },
  UETR: { name: 'Unique End-to-end Transaction Reference', meaning: 'Universal unique reference to track the transaction end to end.', explain: 'A random identifier that should never repeat at any bank in the world, so everyone handling the payment can follow it with the same number.', parts: [{ label: 'Format', text: 'UUID: 36 characters in 8-4-4-4-12 groups separated by hyphens.' }, { label: 'v4', text: 'The first character of the third group (4…) marks a version 4 UUID, generated at random.' }], note: 'Different from EndToEndId. Whether it is mandatory depends on the version and the scheme rules.' },
  PmtTpInf: { name: 'Payment Type Information', meaning: 'Characteristics describing what kind of payment it is and how to handle it.', note: 'A code in this block is not enough to deduce how the whole system operates.' },
  ClrChanl: { name: 'Clearing Channel', meaning: 'Clearing channel through which the instruction should be processed.', parts: [{ label: 'RTNS', text: 'Real Time Net Settlement system (this sample’s value).' }, { label: 'RTGS', text: 'Real-time gross settlement.' }, { label: 'MPNS', text: 'Mass payment net system.' }, { label: 'BOOK', text: 'Book transfer within the same institution.' }], equivalent: 'Process it through a real-time net settlement channel.', note: 'It is an indication in the message; it does not prove a real system uses that model.' },
  LclInstrm: { name: 'Local Instrument', meaning: 'Identifies a payment instrument specific to a community or scheme.', explain: 'Lets you say “this payment is product X of my scheme”. It can be expressed with an external code list value (Cd) or a proprietary value (Prtry), as in the sample.', note: 'The meaning of the value is set by the scheme, not by ISO.' },
  Prtry: { name: 'Proprietary', meaning: 'Value defined by a community, scheme or implementation.', note: 'The tag is standard; the meaning of the value is found in the rules of the context.' },
  IntrBkSttlmAmt: { name: 'Interbank Settlement Amount', meaning: 'Amount settled between the institutions.', explain: 'The money that will move between the instructing bank and the bank receiving the instruction. It carries the currency in an attribute (Ccy) and the figure as content.', parts: [{ label: 'Ccy="XXX"', text: 'Attribute: the currency of the amount.' }, { label: '250.00', text: 'Content: the figure, with a decimal point.' }], equivalent: '250.00 in the given currency must be settled between the banks.', note: 'It is an instruction, not confirmation that the money moved.' },
  '@Ccy': { name: 'Currency · currency attribute', meaning: 'Currency of the amount this attribute belongs to.', explain: 'An attribute is data written inside the opening tag. Ccy uses three-letter ISO 4217 codes (for example USD, EUR, DOP).', parts: [{ label: 'XXX', text: 'ISO 4217 code for “no currency”. Used here on purpose so the example does not represent real money.' }], note: 'An attribute is not a child element: it has no tag of its own, it sits inside <IntrBkSttlmAmt ...>.' },
  IntrBkSttlmDt: { name: 'Interbank Settlement Date', meaning: 'Date the payment should be settled between institutions.', note: 'Uses YYYY-MM-DD, without time. It is the planned date, not evidence of settlement.' },
  ChrgBr: { name: 'Charge Bearer', meaning: 'Who bears the transaction charges.', parts: [{ label: 'SLEV', text: 'Following the service level rules (this sample’s value).' }, { label: 'DEBT / CRED', text: 'Borne by the debtor or the creditor.' }, { label: 'SHAR', text: 'Shared: each side pays its own bank’s charges.' }], note: 'SLEV does not mean “no charges”: it refers to whatever the scheme says.' },
  InstgAgt: { name: 'Instructing Agent', meaning: 'Bank giving the instruction on this leg.', explain: 'In a payment chain, each leg has someone instructing and someone receiving the instruction. InstgAgt is who gives it in this message.', equivalent: 'On this leg, BANK_A (AAAADODX) is the one instructing.', note: 'It is a payment role, not a delivery role. It does not have to match AppHdr/Fr.' },
  InstdAgt: { name: 'Instructed Agent', meaning: 'Bank receiving the instruction on this leg.', equivalent: 'On this leg, BANK_B (BBBBDODX) receives the instruction.', note: 'Do not replace it with AppHdr/To: one is the message receiver, the other the payment receiver.' },
  Dbtr: { name: 'Debtor', meaning: 'Who pays: the party owing the amount. Here CUSTOMER_A.', explain: 'The person or company whose money goes out. Not their bank: their bank is the DbtrAgt.', note: 'Party ≠ agent: CUSTOMER_A pays; BANK_A provides the service.' },
  Nm: { name: 'Name', meaning: 'Name of the party in the containing block.', note: 'The path decides whose it is: under Dbtr it is the payer, under Cdtr the payee.' },
  DbtrAcct: { name: 'Debtor Account', meaning: 'The payer’s account the money leaves from.', explain: 'Inside goes the account identification: an IBAN (<Id><IBAN>) if the country uses it, or another identifier (<Id><Othr><Id>) if not. This sample uses Othr.', note: 'Not the account of the payer’s bank (DbtrAgtAcct).' },
  Id: { name: 'Identification', meaning: 'Identification inside the object given by the path.', note: 'As a block it groups a choice (IBAN or Othr); as a leaf it holds the actual identifier.' },
  Othr: { name: 'Other', meaning: 'A way to identify an account that is not an IBAN.', explain: 'ISO allows identifying an account with an IBAN or with another identifier (Othr/Id). Countries that do not use IBAN rely on this option; it is used here to show the alternative.', equivalent: 'This account is not identified by IBAN but by its own number.', note: 'The value does not reveal the account type by its name. With an IBAN, the XML would say <Id><IBAN>DO58AAAA…</IBAN></Id>.' },
  DbtrAgt: { name: 'Debtor Agent', meaning: 'The payer’s bank: the institution holding their account.', equivalent: 'CUSTOMER_A’s account is at BANK_A.', note: 'BANK_A is the agent; CUSTOMER_A is the party.' },
  DbtrAgtAcct: { name: 'Debtor Agent Account', meaning: 'Account of the payer’s bank at its servicing agent in the chain.', note: 'Do not assume it is the system settlement account just because of the fictitious name of the value.' },
  CdtrAgt: { name: 'Creditor Agent', meaning: 'The payee’s bank: the institution holding their account.', equivalent: 'CUSTOMER_B’s account is at BANK_B.', note: 'BANK_B is the agent; CUSTOMER_B is the party.' },
  CdtrAgtAcct: { name: 'Creditor Agent Account', meaning: 'Account of the payee’s bank at its servicing agent in the chain.', note: 'Not the payee’s account. Its specific role needs the scheme context.' },
  Cdtr: { name: 'Creditor', meaning: 'Who gets paid: the party owed the amount. Here CUSTOMER_B.', note: 'Identifying the payee does not prove their account has already been credited.' },
  CdtrAcct: { name: 'Creditor Account', meaning: 'The payee’s account the money should reach.', explain: 'Like DbtrAcct: inside goes an IBAN or, if the country does not use it, Othr/Id. The payee’s bank uses it to find the account.', note: 'Different from the account of the payee’s bank (CdtrAgtAcct).' },
  Purp: { name: 'Purpose', meaning: 'What the payment is for: a classification of its reason (payroll, taxes, etc.).', explain: 'It can be expressed with an ISO external code list value (Cd) or a proprietary value (Prtry).', note: 'Not the same as the free-text remittance (RmtInf).' },
  RmtInf: { name: 'Remittance Information', meaning: 'Information so the payee knows what is being paid.', explain: 'Links the payment to what it settles: an invoice, a contract, an instalment. It can be free text (Ustrd) or structured (Strd).', note: 'Helps reconciliation, but it does not represent a payment status.' },
  Ustrd: { name: 'Unstructured', meaning: 'Free text describing the payment.', note: 'The phrase is fictitious. Free text does not replace the transaction identifiers.' },
}

export function namespaceNoteEn(value: string): Omit<FieldNote, 'concept'> {
  const base = { name: 'XML namespace', meaning: 'Declares the vocabulary this tag and the ones inside it belong to.', explain: 'xmlns is not payment data. It is technical information telling the XML reader which dictionary to use for the tag names. It is inherited inwards until another tag declares a new one.' }
  if (value.startsWith('urn:iso:std:iso:20022:tech:xsd:')) {
    const message = value.split(':').pop() ?? ''
    const [area, number, variant, version] = message.split('.')
    return {
      ...base,
      parts: [
        { label: 'urn', text: 'Uniform Resource Name: a unique name. It is not a web address you can open.' },
        { label: 'iso:std:iso:20022', text: 'The naming authority: the ISO 20022 standard.' },
        { label: 'tech:xsd', text: 'A technical definition in XML Schema (XSD).' },
        { label: message, text: area === 'head' ? 'The business application header, version 02.' : `Message ${area}.${number}, variant ${variant}, version ${version}.` },
      ],
      equivalent: `Read everything inside with the official ISO 20022 dictionary for ${message}.`,
      note: 'Two tags can share a name in different vocabularies: the namespace tells them apart. AppHdr and Document declare different namespaces.',
    }
  }
  const parts = value.split(':')
  const last = parts[parts.length - 1]
  return {
    ...base,
    parts: [
      { label: 'urn', text: 'Uniform Resource Name: a unique name, not a web address.' },
      ...(parts[1] === 'example' ? [{ label: 'example', text: 'Marks an illustrative or fictitious namespace, typical of documentation and examples.' }] : []),
      ...(parts[2] ? [{ label: parts[2], text: 'Name of the vocabulary or transport format (fictitious here).' }] : []),
      ...(parts.includes('xsd') ? [{ label: 'xsd', text: 'Defined with an XML Schema.' }] : []),
      ...(last && last !== parts[2] ? [{ label: last, text: 'Schema name and version (stp version 1.0).' }] : []),
    ],
    equivalent: 'Create a DataPDU container and read its tags with the example transport vocabulary “stp 1.0”.',
    note: 'A real message would use its transport platform’s namespace. Here “example” makes clear it is not a real format.',
  }
}

export const prtryNotesEn = {
  local: { name: 'Proprietary local instrument', meaning: 'TEST is the fictitious local instrument code.', explain: 'When a scheme does not use the ISO code list, it puts its own value in Prtry.', equivalent: 'This payment belongs to the scheme’s “TEST” instrument.', note: 'ISO defines LclInstrm/Prtry, but gives TEST no universal meaning.' },
  purpose: { name: 'Proprietary purpose', meaning: '999 is the fictitious classification of the payment purpose.', equivalent: 'The reason for the payment is “999” according to the scheme’s own list.', note: 'The same Prtry name appears in other blocks with another meaning. The full path is essential.' },
}
