// Copies the Fluent Emoji icons used by the reference UI into public/ as
// standalone SVG files and regenerates the typed name list.
// Source: Microsoft Fluent Emoji (MIT) via the @iconify-json/fluent-emoji dev dependency.
// Run with `npm run icons` after editing the list below.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'

const names = [
  // scales of the encyclopedia
  'building-construction', 'high-voltage', 'light-bulb', 'incoming-envelope', 'page-facing-up', 'books', 'compass', 'globe-showing-americas',
  // systems and architecture
  'classical-building', 'bank', 'satellite-antenna', 'electric-plug', 'mobile-phone', 'gear', 'link', 'world-map', 'puzzle-piece', 'handshake',
  // money and settlement
  'balance-scale', 'abacus', 'coin', 'money-with-wings', 'stopwatch', 'locked', 'scroll', 'triangular-ruler',
  // operation concepts
  'busts-in-silhouette', 'bust-in-silhouette', 'id-button', 'key', 'label', 'hourglass-not-done', 'magnifying-glass-tilted-left', 'check-mark-button',
  'no-entry', 'right-arrow-curving-left', 'counterclockwise-arrows-button', 'repeat-button', 'bar-chart', 'package',
  // messages and documents
  'memo', 'clipboard', 'inbox-tray', 'outbox-tray', 'bell', 'ledger', 'stop-sign', 'card-index-dividers', 'card-file-box', 'e-mail', 'receipt',
  // spaces
  'bookmark', 'open-book', 'spiral-notepad',
]

const require = createRequire(import.meta.url)
const set = JSON.parse(readFileSync(require.resolve('@iconify-json/fluent-emoji/icons.json'), 'utf8'))
const out = new URL('../public/icons/fluent/', import.meta.url)
rmSync(out, { recursive: true, force: true })
mkdirSync(out, { recursive: true })
for (const name of names) {
  const icon = set.icons[name]
  if (!icon) throw new Error(`Unknown Fluent Emoji icon: ${name}`)
  const width = icon.width ?? set.width ?? 32
  const height = icon.height ?? set.height ?? 32
  writeFileSync(new URL(`${name}.svg`, out), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">${icon.body}</svg>\n`)
}
writeFileSync(new URL('LICENSE.txt', out), `Icons: Fluent Emoji by Microsoft Corporation
https://github.com/microsoft/fluentui-emoji
License: MIT — https://github.com/microsoft/fluentui-emoji/blob/main/LICENSE
Extracted from @iconify-json/fluent-emoji by scripts/fluent-icons.mjs.
`)
writeFileSync(new URL('../src/components/reference/iconNames.ts', import.meta.url), `// Generated by scripts/fluent-icons.mjs — do not edit by hand.
export const iconNames = ${JSON.stringify(names, null, 2).replace(/"/g, "'")} as const
export type IconName = (typeof iconNames)[number]
`)
// Browser icon: the same mark as the menu logo (.payment-mark) — a mint-to-blue
// tile with the 3D "money with wings".
const mark = set.icons['money-with-wings']
writeFileSync(new URL('../public/aula-icon.svg', import.meta.url), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <defs><linearGradient id="tile" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#1ae0ba"/><stop offset="1" stop-color="#2296ff"/></linearGradient></defs>
  <rect width="64" height="64" rx="15" fill="url(#tile)"/>
  <svg x="9" y="9" width="46" height="46" viewBox="0 0 32 32">${mark.body}</svg>
</svg>
`)
console.log(`Wrote ${names.length} icons to public/icons/fluent/ and public/aula-icon.svg`)
