import { Link } from 'react-router-dom'
import { ArrowRight, BookOpen, FlaskConical, ListTree, CheckCheck, Bookmark, FileQuestion } from 'lucide-react'
import { useL } from '@/i18n/reference/useLang'

// Each text is [Spanish, English].
const sections = [
  { title: ['Estudio guiado', 'Guided study'], icon: BookOpen, text: ['El recorrido original por fundamentos, ISO 20022 y SGPI.', 'The original path through fundamentals, ISO 20022 and SGPI.'], links: [[['Continuar y progreso', 'Continue and progress'], '/classic/dashboard'], [['Mapa de aprendizaje', 'Learning map'], '/learn/fast-payments'], [['Caso público SGPI', 'SGPI public case'], '/learn/spi-dominicana']] },
  { title: ['Atlas clásico', 'Classic atlas'], icon: ListTree, text: ['Catálogo, árboles de mensajes y glosario de la versión anterior.', 'Catalogue, message trees and glossary from the previous version.'], links: [[['Atlas ISO 20022', 'ISO 20022 atlas'], '/atlas'], [['Catálogo de mensajes', 'Message catalogue'], '/atlas/messages'], [['Glosario', 'Glossary'], '/glossary']] },
  { title: ['Laboratorios', 'Labs'], icon: FlaskConical, text: ['Simulación, investigación y ejercicios técnicos.', 'Simulation, investigation and technical exercises.'], links: [[['Simulador', 'Simulator'], '/lab/simulator'], [['Investigation Workbench', 'Investigation Workbench'], '/lab/debugger'], [['XML Lab', 'XML Lab'], '/lab/xml'], [['Identificadores', 'Identifiers'], '/lab/identifiers'], [['Reject vs. Return', 'Reject vs. Return'], '/lab/reject-return'], [['Detectar errores XML', 'Spot XML errors'], '/lab/break-message']] },
  { title: ['Práctica', 'Practice'], icon: CheckCheck, text: ['Escenarios y revisión de lo aprendido.', 'Scenarios and review of what you learned.'], links: [[['Sesión de práctica', 'Practice session'], '/practice/session'], [['Escenarios', 'Scenarios'], '/practice/scenarios'], [['Quiz', 'Quiz'], '/practice/quiz'], [['Confusiones frecuentes', 'Common confusions'], '/confusions']] },
  { title: ['Mi biblioteca', 'My library'], icon: Bookmark, text: ['Favoritos y progreso guardados en este navegador.', 'Bookmarks and progress saved in this browser.'], links: [[['Guardados', 'Saved'], '/saved'], [['Progreso', 'Progress'], '/progress']] },
  { title: ['Info extra', 'Extra info'], icon: FileQuestion, text: ['Preguntas de validación y lienzo compartido.', 'Validation questions and shared canvas.'], links: [[['Abrir Info extra', 'Open Extra info'], '/learn/info-extra']] },
] as const
export function LegacyHub() {
  const L = useL()
  return <div className="ref-page"><header className="border-b border-border pb-6"><div className="ref-eyebrow text-party">AULA LIBRE DE PAGOS / {L('COLECCIÓN ORIGINAL', 'ORIGINAL COLLECTION')}</div><h1 className="mt-2 text-3xl font-semibold">{L('Estudio clásico', 'Classic study')}</h1><p className="mt-2 text-sm text-muted">{L('Lecciones, laboratorios y práctica.', 'Lessons, labs and practice.')}</p></header><div className="grid gap-x-10 sm:grid-cols-2">{sections.map((section) => <section key={section.title[0]} className="ref-section"><h2 className="flex items-center gap-2 text-base font-semibold"><section.icon size={18} className="text-party" />{L(section.title[0], section.title[1])}</h2><p className="mt-2 text-sm text-muted">{L(section.text[0], section.text[1])}</p><div className="mt-4 space-y-3">{section.links.map(([label, to]) => <Link key={to} to={to} className="flex items-center justify-between text-sm text-primary hover:underline">{L(label[0], label[1])}<ArrowRight size={13} /></Link>)}</div></section>)}</div></div>
}
